### ISSUE TITLE
[enterprise-3.7] Edit suggested in file using_images/index.adoc

### ISSUE THREAD

**Issue by timabell** [openshift/openshift-docs#10161]
### Which section(s) is the issue in?

"Overview"

### What needs fixing?

The "openshift3 repository" link is broken - redirects to root page

**Comment by vikram-redhat** [comment]
@tmorriso-rh - PTAL.

**Comment by tmorriso-rh** [comment]
Starting with 3.7, users are directed to the index page. There is a note on the page that ask users to browse or search for the image they need.

Cc: @vikram-redhat

**Comment by vikram-redhat** [comment]
@tmorriso-rh Hey. I think we should update the page to point to the Container Catalog instead of the registry. Red Hat registry now redirects to the Red Hat Container catalog.

The openshift3 registry link should now point to: https://access.redhat.com/containers/?tab=security&start=10#/product/RedHatOpenshiftContainerPlatform and that whole paragraph should probably be rewritten with links to registry.access.redhat.com replaced with the new links to these images.

**Comment by tmorriso-rh** [comment]
Work in progress: https://github.com/openshift/openshift-docs/pull/10605

**Comment by tmorriso-rh** [comment]
CP via:

3.7: https://github.com/openshift/openshift-docs/pull/10614
3.9: https://github.com/openshift/openshift-docs/pull/10615
3.10: https://github.com/openshift/openshift-docs/pull/10616
