### ISSUE TITLE
[enterprise-3.9] Edit suggested in file apb_devel/cli_tooling.adoc

### ISSUE THREAD

**Issue by akesterton** [openshift/openshift-docs#10436]
### Which section(s) is the issue in?
CLI installation - Prerequsites

### What needs fixing?
APB requires Ansible 2.5 for the openshift_raw module.  Default installation for OpenShift 3.9 is Ansible 2.4. 

Please add this requirements, and pointer to instructions to upgrade the Ansible 2.4 installation.

**Comment by vikram-redhat** [comment]
@gaurav-nelson - PTAL.

**Comment by gaurav-nelson** [comment]
@akesterton 

- https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/apb_cli.md does not mention such a requirement?
-  Is mentioned somewhere else?

**Comment by gaurav-nelson** [comment]
@akesterton Can I get some more information around this? 
I am afraid, I will have to close this one if I do not get a response by Friday, 6th July 2018.

**Comment by akesterton** [comment]
Hi

The bundle requires Ansible 2.5 or greater - not the 2.4 shipped with OpenShift 3.9.  Ansible 2.5 breaks the OpenShift installer.  There is no mention of the required version of Ansible in the documentation.  I think this should be explicit if this is required by APB.

Does that help?

regards

anthony

Anthony Kesterton, Senior Solution Architect, Red Hat
akesterton@redhat.com, +44 7971 780758

**Comment by gaurav-nelson** [comment]
Thank you @akesterton for responding.

I will put together a PR to rectify this.

**Comment by gaurav-nelson** [comment]
@akesterton Can you please check https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/issues/313 and contribute to the related discussion there?

**Comment by gaurav-nelson** [comment]
Thanks @akesterton for providing details in the ansible-playbook-bundle issue. 

I think the problem here is that in our docs (https://docs.openshift.com/container-platform/3.9/apb_devel/cli_tooling.html#apb-devel-cli-install-prereqs-access-permissions)  we have the following instruction:
![image](https://user-images.githubusercontent.com/23069445/42740190-fca235f4-88e6-11e8-9cdc-cebf0a5b70ef.png)
The link `openshift-permissions.template.yaml` points to `https://raw.githubusercontent.com/ansibleplaybookbundle/ansible-playbook-bundle/master/templates/openshift-permissions.template.yaml` in **master** branch. And as per https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/issues/313#issuecomment-404892699 For OCP 3.9 this link should instead point to `https://raw.githubusercontent.com/ansibleplaybookbundle/ansible-playbook-bundle/release-1.1/templates/openshift-permissions.template.yaml` which is in branch **release-1.1**.

I think this will solve the issues customer is facing. Can you confirm?

**Comment by gaurav-nelson** [comment]
@akesterton Can you please check https://github.com/openshift/openshift-docs/issues/10436#issuecomment-405131427

I can fix this one after the go ahead.

**Comment by akesterton** [comment]
Hi

My apologies, the filters on my email client pushed this to a folder I have not read for a while.  I will check on this tomorrow and get back to you.

regards

anthony

Anthony Kesterton, Senior Solution Architect, Red Hat
akesterton@redhat.com, +44 7971 780758

**Comment by akesterton** [comment]
I am unable to tell if the revised instructions will make a difference.
