### ISSUE TITLE
[enterprise-3.9] Edit suggested in file install_config/routing_from_edge_lb.adoc

### ISSUE THREAD

**Issue by rearden-steel** [openshift/openshift-docs#10876]
### Which section(s) is the issue in?

On the ramp node:

Set the following variables:

```
# F5_IP=10.3.89.66
# TUNNEL_IP1=10.3.91.216
# TUNNEL_IP2=10.3.91.217 
# CLUSTER_NETWORK=10.128.0.0/1 

```
### What needs fixing?

`# CLUSTER_NETWORK=10.128.0.0/1 
`
->

`# CLUSTER_NETWORK=10.128.0.0/14
`

**Comment by vikram-redhat** [comment]
@bmeng - is this correct?

Doc: https://docs.openshift.com/container-platform/3.9/install_config/routing_from_edge_lb.html

@bfallonf - PTAL and based on @bmeng's response either fix and close or close this issue.

**Comment by bmeng** [comment]
@lihongan Can you help review this issue? The cluster network is incorrect indeed, but I think the whole paragraph of the ramp node needs to be fixed.

**Comment by lihongan** [comment]
Yes, it should be `# CLUSTER_NETWORK=10.128.0.0/14`. 
Here it takes F5 as example to tell how to configure ramp node with ipip tunnel, but it is just demo and cannot be deployed to production since all settings will gone after ramp node (or openvswitch service) restarting. You can add a "Note" before the paragraph if needed.

**Comment by bfallonf** [comment]
Thanks @rearden-steel @lihongan . I've created #11349 for this issue. I have asked a question about the note box I have added, but we can move the conversation to that PR.

I'll close this issue.
