### ISSUE TITLE
Podman (Technology Preview)

### ISSUE THREAD

**Issue by ahardin-rh** [openshift/openshift-docs#11158]
### Which section(s) is the issue in?
3.10 Release Notes
https://github.com/openshift/openshift-docs/pull/11010

### What needs fixing?

Comments from @dmoessne:

Podman (Technology Preview)

  This seems to be confusing as we are also having cri-o. Customers will wonder why we introduce yet another runtime, therefore I'd feel it would be beneficial if we could explain a bit more around why we have this in tech preview and how it is meant to be used (as well how it should be actually used,
  but the same goes in fact to cri-o as well) as well how it differentiates to docker/cri-o ?
  Customers will surly ask, why we have yet another option and what benefits as well as differences to other runtimes are. At least a link explaining this would be great.

**Comment by ahardin-rh** [comment]
@mheon Can you please help me address this feedback?

**Comment by mheon** [comment]
Hi,
On Podman vs CRI-O: CRI-O is a dedicated Kubernetes runtime - it is built exclusively to run containers for Kubernetes. Podman is a more general replacement for the Docker commandline - it can do things CRI-O and crictl cannot (such as restart containers) because Kubernetes does not need them.

For now, CRI-O and Podman have separate containers, but we are making progress towards having them share the same code for launching and managing containers. Once this is done, Podman will be able to see all the containers created by CRI-O (though the opposite will not be true - CRI-O only wants to view and manage containers seen by Kubernetes). This will make Podman a valuable debugging tool for CRI-O - you'll be able to do things to containers that Kubernetes or Openshift command line cannot. Until this happens, Podman is still a valuable debugging tool for images - it shares image storage with CRI-O and can do many things that Kubernetes and Openshift cannot.

To be clear, we do not see Openshift ever running on top of Podman directly, without CRI-O. Any framing should be as CRI-O as an alternative to Docker, and Podman as a supplement to CRI-O to enhance the debugging experience. Podman can also replace the Docker CLI in places where Kubernetes is not involved, but I don't think that's really that relevant to the Openshift docs.

A good explanation of their relationship is https://blog.openshift.com/crictl-vs-podman/ --- it more focuses on crictl, but it does somewhat explain the difference between Podman and CRI-O and our goals for the two.

I'll follow up with further details on Monday.

**Comment by ahardin-rh** [comment]
@mheon Thanks for this! Added a link to that blog in https://github.com/openshift/openshift-docs/pull/11254, but let me know if we need to add more.
