### ISSUE TITLE
What to use instead of openshift_node_kubelet_args in 3.10?

### ISSUE THREAD

**Issue by dharmit** [openshift/openshift-docs#12623]
### Which section(s) is the issue in?
Configuring Inventory File page's [Configuring Host Variables](https://docs.okd.io/3.10/install/configuring_inventory_file.html#configuring-host-variables) has details about `openshift_node_kubelet_args` while openshift-ansible repo mentions that [it's deprecated](https://github.com/openshift/openshift-ansible/blob/release-3.10/inventory/hosts.example#L815). How are we supposed to configure kubelet args through Ansible inventory file starting 3.10?

### What needs fixing?
Inconsistency between two repos (openshift-docs & openshift-ansible) around usage of `openshift_node_kubelet_args` variable.

**Comment by bysnupy** [comment]
@dharmit , 

There is a new configuration example instead of `openshift_node_kubelet_args ` in the same page - [Configuration Host Variables](https://docs.okd.io/3.10/install/configuring_inventory_file.html#configuring-host-variables).

- [Node Group Definitions](https://docs.okd.io/3.10/install/configuring_inventory_file.html#configuring-inventory-node-group-definitions)

> openshift_node_groups=[{'name': 'node-config-master',  'labels': ['node-role.kubernetes.io/master=true']}, 
>                                              {'name': 'node-config-infra', 'labels': ['node-role.kubernetes.io/infra=true']}, 
>                                              {'name': 'node-config-compute', 
>                                               'labels': ['node-role.kubernetes.io/compute=true'], 
>                                               'edits': [{ 'key': 'kubeletArguments.pods-per-core','value': ['20']}]}]
> 

But, it's not user friendly...

**Comment by kalexand-rh** [comment]
I think this change is covered in @bysnupy's PRs. (Thank you) Closing.
