### ISSUE TITLE
[enterprise-4.2] IPAM DHCP used in YAML configuration may not be good due to bug 1754682

### ISSUE THREAD

**Issue by weliang1** [openshift/openshift-docs#16885]
### Which section(s) is the issue in?
multiple networks

### What needs fixing?
The value of IPAM used in most YAML configures sample file in this section is DHCP, due to  https://bugzilla.redhat.com/show_bug.cgi?id=1754682, IPAM with type DHCP does not work in v4.2 at all, we may need mention this at the beginning of this section or some where.

**Comment by jboxman** [comment]
@weliang1, thanks for reporting this!

**Comment by jboxman** [comment]
I'm going to include updates for this in https://github.com/openshift/openshift-docs/pull/16983.

**Comment by jboxman** [comment]
I added (https://github.com/openshift/openshift-docs/pull/16983/files#diff-ce2ac1ce8515c024b73a9ea081ca05b5R27):

>In {product-title} 4.2.0, if you attach a Pod to an additional network that uses
DHCP for IP address management, the Pod will fail to start.
This will be fixed in a future release.
For more information, see link:https://bugzilla.redhat.com/show_bug.cgi?id=1754686[BZ#1754686].

**Comment by jboxman** [comment]
@vikram-redhat, this is a straightforward fix and I think the above commit resolves it.
