### ISSUE TITLE
HPA Doc 404s When Requested From Search Bar

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/openshift-docs#1691]
When searching `Horizontal Pod Autoscaler` from the search bar, the first article that comes up is the [Pod Autoscaling](https://docs.openshift.org/latest/dev_guide/pod_autoscaling.html) doc. Clicking this link on Firefox 40.0.3 intermittently gives me an nginx 404 screen. Navigating to the page using the link on the sidebar does not.

**Comment by adellape** [comment]
@stevekuznetsov Have you only noticed this in the Origin docs? Versus https://docs.openshift.com/enterprise.

**Comment by stevekuznetsov** [comment]
No, only at https://docs.openshift.org/latest/

**Comment by adellape** [comment]
Thanks.

FYI @nhr

**Comment by nhr** [comment]
I've tested this a few times on a few different browsers (including FF) and I'm not able to reproduce it. However - the search functionality is provided by a Google custom search, so it is possible that this was an issue in their embeddable search stuff that has since been resolved. I advise closing this for now but we can reopen if this starts happening with more regularity.

**Comment by stevekuznetsov** [comment]
Yeah, I can't seem to reproduce it now, either.
