### ISSUE TITLE
OpenShift 3.2 Release Notes

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-docs#1700]
All release notes relevant for 3.2

**Comment by smarterclayton** [comment]
By default, services with externalIPs will be rejected since they can be used to allow services to pretend to act as nodes in some cases.  A new config flag has been added to `master-config.yaml`, `networkConfig.externalIPNetworkCIDR` that controls the allowable values for external IPs. By default it will be empty which rejects all values.  Admins can set it to `0.0.0.0/0` to emulate behavior in 3.1.

**Comment by pmorie** [comment]
FSGroup is now enabled by default in the `restricted` and `hostns` security context constraints.  This means that pods matched against those SCCs will:

1.  Have the `pod.spec.securityContext.fsGroup` field populated to a namespace-wide allocated value automatically
2.  Have their emptyDir-derived (emptyDir, gitRepo, secret, configMap, downwardAPI) and block device volumes (basically every network volume except ceph and nfs) owned by the FSGroup
3.  Run with the FSGroup in each container's list of supplemental groups

**Comment by jwforres** [comment]
Web console enhancements:

- Brand new theme that changes the look and feel of the navigation, tabs, and other page elements
- Form-based editor for build configurations for modifying commonly edited fields
- All browse resource pages (e.g viewing a particular pod) have a tab for Events related to that pod.  All events pages now support filtering and sorting
- Add/edit resource constraints for your containers during "Add to Project" or later from the deployment configuration
- About page provides end users with information about the product version, `oc` CLI download locations, and a quick access to their current token to login using the CLI
- Customize CLI download URLs and documentation URLs through console extensions
- Edit a project's display name and description from the Settings page

**Comment by fabianofranz** [comment]
Web console:

- List existing persistent volume claims and attach them to deployments and deployment configs.

**Comment by kargakis** [comment]
* `oc create route` for creating secured routes in the cli

**Comment by danwinship** [comment]
The default values for pod networking have changed:
- `clusterNetworkCIDR` (`osm_cluster_network_cidr` in ansible) now defaults to `10.128.0.0/14` (`10.128.0.0` - `10.131.255.255`) rather than `10.1.0.0/16`.
- `hostSubnetLength` (`osm_host_subnet_length` in ansible) now defaults to `9` rather than `8` (meaning each node will be assigned a `/23` subnet rather than a `/24`)

**Comment by soltysh** [comment]
* image import changes, which allow specifying per tag import/reference
* allowing importing images from private repositories using secrets
* allowing scheduling image imports
* limiting no of imported images

**Comment by dobbymoodge** [comment]
Policy plugin:
* Added PodNodeConstraints admission control plugin
  * Constrains use of NodeName field in Pod spec to roles which have the `pods/binding` permission
  * Allows administrators, via NodeSelectorLabelBlacklist, to specify Node labels which can only be specified in the NodeSelector field in PodSpec by roles with the `pods/binding` permission

**Comment by pweil-** [comment]
Two new fields have been added to SCCs:

1.  `ReadOnlyRootFilesystem` allows an admin to force containers to run with a read only root file system.  
     1.  If set to true then containers will be required to run with a read only root file system by their `SecurityContext`.  Containers that do not set this value to true will be defaulted.  Containers that explicitly set this value to false will be rejected.
     1.  If set to false containers may use a read only root file system if they wish but will they will not be forced to run with a read only root file system
1.  `Volumes` allows an admin full control over which volume plugins may be specified.  In order to maintain backwards compatibility the `AllowHostDirVolumePlugin` field will have precedence over the `Volumes` field for the host mounts.  You may use the value `*` to allow all volumes.

SCCs should be reconciled after the upgrade to pick up new defaults.

**Comment by miminar** [comment]
- Added an ability to restrict number of unique image references in the project using quota.
  - Using `openshift.io/imagestreamtags` and `openshift.io/imagestreamimages` resources.
- Allowed to restrict maximal size of image that can be pushed to project using limit ranges.
  - By setting a `Max["storage"]` on `openshift.io/image-size` limit type.

**Comment by miminar** [comment]
Known issue [#7792](https://github.com/openshift/origin/issues/7792).

- internally managed image cannot be pulled from an image reference referencing another image stream

To make sure your built image image is pullable, either:

1. avoid re-tagging it to any other image stream (e.g. using `oc tag`)
2. instead of tagging it, push the built image to the desired image stream [manually](https://docs.openshift.com/enterprise/3.1/install_config/install/docker_registry.html#access-pushing-and-pulling-images)

**Comment by sdodson** [comment]
https://github.com/openshift/origin/pull/8408
 * Permissions on /etc/origin have been tightened to prevent un-privileged users from reading the contents of this directory tree. Admins should ensure that, if necessary, they've provided other means to access the generated CA certificate.

**Comment by sdodson** [comment]
- By default, nodes installed with 1.2 or 3.2 will have dnsmasq installed and configured as the default nameserver for both the host and pods.
- By default, masters installed with 1.2 or 3.2 will run SkyDNS on port 8053 rather than 53. Network access controls must allow nodes to connect to masters on port 8053. This is necessary so that dnsmasq may be configured on all nodes.

**Comment by adellape** [comment]
Published here:

https://docs.openshift.com/enterprise/3.2/release_notes/ose_3_2_release_notes.html

**Comment by nak3** [comment]
@danwinship

> hostSubnetLength (osm_host_subnet_length in ansible) now defaults to 9 rather than 8 (meaning each node will be assigned a /23 subnet rather than a /24)

Is that correct that `osm_host_subnet_length` is default `9`? Our node hosts always have been asigned `/24` subnet (in 3.2). I have checked [1] as well. Could you please confirm if the default value `9` is correct? (I'm sorry if I was wrong.)

[1] https://github.com/openshift/openshift-ansible/blob/3cc2d6b019fa8a05ba480a7425cd654aa051355f/roles/openshift_facts/library/openshift_facts.py#L907-L908

**Comment by danwinship** [comment]
Hm... the code defaults to clusterNetworkCIDR 10.128.0.0/14 and hostSubnetLength 9 if they aren't specified in the config, but you're right, it looks like in at least some cases, openshift-ansible is still writing the old default values to the config... I'm pretty sure this doesn't happen all the time though, just from seeing logs, etc, from users using the new defaults.
