### ISSUE TITLE
[enterprise-4.2] Edit suggested in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by kappert** [openshift/openshift-docs#17440]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.2/installing/installing_vsphere/installing-vsphere.html#installation-dns-user-infra_installing-vsphere

### What needs fixing?

The tabels are not completly visible, i have to select the text to see all the information, see screenshots for the exacht problem.

![Screenshot from 2019-10-18 10-45-32](https://user-images.githubusercontent.com/4837197/67079987-86c4a980-f194-11e9-9780-e69497946314.png)
![Screenshot from 2019-10-18 10-45-53](https://user-images.githubusercontent.com/4837197/67080000-8af0c700-f194-11e9-853a-7a39020a0c3d.png)

**Comment by vikram-redhat** [comment]
Hi @kappert. This is not something we are able to fix right now. We are working towards a way to provide a copy button that should help.

**Comment by jboxman** [comment]
@vikram-redhat, I think the issue is that the entire table -- all of the contents -- overflow and there's a horizontal scroll bar for the entire table.

There's a CSS property, _overflow_, which moderates how this behavior works. The alternative, I think, is to modify the CSS so the entire page has a horizontal scroll bar. Whether this is desirable as an alternative, I can't say.
