### ISSUE TITLE
[enterprise-4.2] Edit suggested in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by rbaumgar** [openshift/openshift-docs#17674]
### Which section(s) is the issue in?
Installing the Cluster Logging and Elasticsearch Operators
Procedure

### What needs fixing?
1. Create Namespaces for the Elasticsearch Operator...
a. Create a Namespace for the Elasticsearch Operator 
b. Run the following command to create the namespace

is exactly the same as
c. Create a Namespace for the Cluster Logging Operator
d. Run the following command to create the namespace

**Comment by mburke5678** [comment]
@rbaumgar Fair point. Due to an RFE, I was in the file and changed the wording in that topic. It now says:

```
1 .Create a Namespace for the Cluster Logging Operator:

1a.  Create a Namespace object YAML file (for example, clo-namespace.yaml) for the Cluster Logging Operator:

1b.  Create the Namespace:
$ oc create -f <file-name>.yaml
```
And the same for the Elasticsearch Operator. I just want to emphasize the need to create the YAML needed. I am closing this issue for now. Let me know if this wording still seems incorrect and I can take a look.  
Thanks for your comment!
