### ISSUE TITLE
[enterprise-4.2] Edit suggested in file operators/olm-restricted-networks.adoc

### ISSUE THREAD

**Issue by therevoman** [openshift/openshift-docs#17695]
### Which section(s) is the issue in?
item 6 for the custom-registry

### What needs fixing?
image name (changed with 4.2) and file paths.

`FROM registry.redhat.io/openshift4/ose-operator-registry:v4.2.0 AS builder

COPY manifests manifests

RUN /bin/initializer -o ./bundles.db

FROM scratch

COPY --from=builder /registry/bundles.db /bundles.db
COPY --from=builder /usr/bin/registry-server /registry-server
COPY --from=builder /bin/grpc_health_probe /bin/grpc_health_probe

EXPOSE 50051

ENTRYPOINT ["/registry-server"]

CMD ["--database", "bundles.db"]
`

**Comment by adellape** [comment]
The Dockerfile in the 4.2 docs (the 4.3 docs has a different process) has been updated a few times since this report, which I believe addresses the requested changes here:

https://github.com/openshift/openshift-docs/pull/18350
https://github.com/openshift/openshift-docs/pull/19036
https://github.com/openshift/openshift-docs/pull/20825

If there are still issues, please reopen. Thank you!
