### ISSUE TITLE
[enterprise-4.2] Edit suggested in file migration/migrating-openshift-3-to-4.adoc

### ISSUE THREAD

**Issue by mwitzenm** [openshift/openshift-docs#17879]
### Which section(s) is the issue in?
Title

### What needs fixing?
Migrating OpenShift Container Platform 3.x to 4.2

I would suggest we change "3.x to 4.3" to "3.7+ to 4.x" to be explicit because it does indeed matter

**Comment by vikram-redhat** [comment]
Thanks for the feedback @mwitzenm. I believe this was a conscious decision to go with 3.x instead of a particular y number.

@apinnick if you have any other insight.

**Comment by apinnick** [comment]
@mwitzenm @vikram-redhat 
For the first release (OpenShift Container Platform 4.2 / CAM 1.0), the only use case we are supporting is 3.x to 4.2. For the next minor release (CAM 1.0.1), we will be adding the 4.1 to 4.2 migration use case. When 4.3 appears, we'll change the '4.2' to 4.x'. 

Because we are supporting 3>4 and 4>4 migrations, in parallel, it was decided to NOT to use 4.x instead of 4.2.

RE: 3.7+. We do not use "+" for version numbers. Rather, the style guide (at least, the one I was told to follow) specifies "3.7 and later" (earlier/later, rather than older/newer) for versions. This would have made the title rather long, so I chose to use 3.x instead of 3.7+. Hope this clarifies things. You are correct, but we don't use "+" for versions, AFAIK.
