### ISSUE TITLE
Add image version info to ShiftStack docs

### ISSUE THREAD

**Issue by maxwelldb** [openshift/openshift-docs#18200]
### Which section(s) is the issue in?

OpenStack on OpenShift installation docs - RHCOS image section

### What needs fixing?

Quoting from Slack:

>who did the downstream docs? specially the section regarding the RHCOS image. We need to add something similar to what the baremetal folks has included to make it more clear: "The RHCOS images might not change with every release of OpenShift Container Platform. You must download images with the highest version that is less than or equal to the OpenShift Container Platform version that you install. Use the image versions that match your OpenShift Container Platform version if they are available."

**Comment by codyhoag** [comment]
@maxwelldb I was told by the OpenStack team that the RHCOS image creation module should be removed for 4.3, since it is no longer a necessary step in the installation process #18774. I'll go ahead and remove the `enterprise-4.3` label since the module is no longer there.

For 4.2, I can add that note you summarized in the description. Let me know if you have any objections. Thanks!

**Comment by maxwelldb** [comment]
Thanks!

**Comment by codyhoag** [comment]
PR has been reviewed and merged. https://github.com/openshift/openshift-docs/pull/19311
