### ISSUE TITLE
[enterprise-4.2] Edit suggested in file storage/persistent-storage/persistent-storage-aws.adoc

### ISSUE THREAD

**Issue by kasturinarra** [openshift/openshift-docs#19217]
### Which section(s) is the issue in?
Maximum Number of EBS Volumes on a Node

### What needs fixing?
Variable KUBE_MAX_PD_VOLS is no longer exposed now with OCP4.x, since kubernetes 1.11 introduced dynamic volume limits and once it is enabled Kubernetes automatically
 determines the node type and supports the appropriate number of attachable
 volumes for the node.

**Comment by rheinzma** [comment]
While https://v1-16.docs.kubernetes.io/docs/concepts/storage/storage-limits/#dynamic-volume-limits mentions dynamic support for AWS, GCP, Azure and how to handle this in CSI. How does this work with Cinder etc. ?

**Comment by bobfuru** [comment]
Thank you, @kasturinarra This was addressed in your bug in https://bugzilla.redhat.com/show_bug.cgi?id=1794729. It was fixed in 4.5, 4.6 with https://github.com/openshift/openshift-docs/pull/25348, fixed in 4.4 with https://github.com/openshift/openshift-docs/pull/25411, and fixed in 4.3 with https://github.com/openshift/openshift-docs/pull/25413. (`enterprise-4.2` branch is no longer supported).
Closing issue.
