### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/registry/deploy_registry_existing_clusters.adoc

### ISSUE THREAD

**Issue by magick93** [openshift/openshift-docs#19346]
### Which section(s) is the issue in?

[Deploying the Registry](https://docs.openshift.com/container-platform/3.11/install_config/registry/deploy_registry_existing_clusters.html#deploy-registry)

### What needs fixing?

> To deploy the integrated container image registry, use the `oc adm registry` command as a user with cluster administrator privileges. For example:
> ```
> $ oc adm registry --config=/etc/origin/master/admin.kubeconfig \ 
>    --service-account=registry \
>    --images='registry.redhat.io/openshift3/ose-${component}:${version}
> ```

There is no mention anywhere on the current docs as to what the `${component}:${version}` values should be.

**Comment by bobfuru** [comment]
Thank you for the suggestion, @magick93. This issue was addressed in https://github.com/openshift/openshift-docs/pull/25904 and the change is now live in OCP 3.11 docs here: https://docs.openshift.com/container-platform/3.11/install_config/registry/deploy_registry_existing_clusters.html#deploy-registry
