### ISSUE TITLE
Update user/identity section to describe manual/API-driven user provisioning

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#1982]
/architecture/additional_concepts/other_api_objects.html#identity describes how an identity and user object is automatically created by the system on login.

When using the "lookup" mappingMethod, that provisioning is expected to be done by an external system, via the API.

Update that section to add information about exactly what should be done to provision a user:

Input: identity provider name, identity provider user id, openshift user name
1. create an Identity object with name `<identity provider name>:<identity provider user id>`
2. create a User object with name `<openshift user name>`
3. create a UserIdentityMapping object with name `<identity provider name>:<identity provider user id>` referencing the created User and Identity names

**Comment by mburke5678** [comment]
@liggitt Culling through older issues. Is this issue still relevant? 
It _looks_ like you are asking for a procedure here, rather than just having the sections? 
Are the steps above only for the `lookup` mapping method? 
Should the info be here instead/also?
https://docs.openshift.org/latest/install_config/configuring_authentication.html#mapping-identities-to-users

**Comment by liggitt** [comment]
yes, describing a procedure (three API creation steps)

```
$ oc create user <username>
$ oc create identity <identity-provider>:<user-id-from-identity-provider>
$ oc create useridentitymapping <identity-provider>:<user-id-from-identity-provider> <username>
```

it could be referenced from the mapping-identies-to-users section as well

**Comment by mburke5678** [comment]
Closing issue. Making updates via https://github.com/openshift/openshift-docs/pull/5290
