### ISSUE TITLE
Github description website points to OKD doc site

### ISSUE THREAD

**Issue by pbergene** [openshift/openshift-docs#20104]
### Which section(s) is the issue in?

Documentation link in github description.  Website field goes to OKD docs. 

### What needs fixing?

Link in description of https://github.com/openshift/openshift-docs links to https://docs.openshift.org/latest/welcome/index.html.  The virtual host on openshift.**org** takes you to the OKD docs.  I could be wrong, but I would expect this to point toto docs on openshift.**com**.

**Comment by jboxman** [comment]
@vikram-redhat, FYI.

**Comment by vikram-redhat** [comment]
OKD docs (docs.okd.io) are the upstream docs for OpenShift docs and are published via this repo so that link isn't incorrect. It should be changed to docs.okd.io or docs.openshift.com. The current link redirects to docs.okd.io and I have requested it be changed properly instead of requiring the redirect.
