### ISSUE TITLE
[enterprise-4.3] Edit suggested in file nodes/nodes/nodes-nodes-audit-log.adoc

### ISSUE THREAD

**Issue by aelicieguo** [openshift/openshift-docs#20749]
### Which section(s) is the issue in?
step 2. Edit the API server CR:

### What needs fixing?

there are no such parameters in apiserver: logLevel and operatorloglevel under spec. I have filed a github issued https://github.com/openshift/api/issues/614. not sure if the error came from CRD or documentation. adding these 2 parameters will get erased by operator. this documentation error is same for version 4.2.

**Comment by mburke5678** [comment]
I believe we are working on this. Not sure at the moment what the course of action is. 
I think that this issue is planned to be fixed in 4.6. Thus, the information should be removed from the docs. However, I have not gotten approval for removing the information yet. 
https://bugzilla.redhat.com/show_bug.cgi?id=1791888

**Comment by mburke5678** [comment]
Section removed from docs: https://github.com/openshift/openshift-docs/pull/20905
