### ISSUE TITLE
"Just run OKD in a container by itself" section of okd.io leads nowhere

### ISSUE THREAD

**Issue by Huge** [openshift/openshift-docs#20916]
### Which section(s) is the issue in?
OKD.io website

### What needs fixing?
The link in "Just run OKD in a container by itself." points to https://docs.okd.io/latest/getting_started/administrators.html#running-in-a-docker-container which is 404, making the whole section worth <0.

@wgordon17 might help?

**Comment by wgordon17** [comment]
Hi @Huge, I apologize for the difficulties encountered. We are tracking this issue in another issue on the okd.io GitHub (https://github.com/openshift-cs/okd.io/issues/100).

Since this doesn't directly affect the documentation team, I would recommend closing this issue, and following the issue on the okd.io website.

I'll push some internal teammates to hopefully address this soon.

In the meantime, the _correct_ link is https://docs.okd.io/3.11/getting_started/administrators.html#running-in-a-docker-container, for running OKD v3 in a container.
