### ISSUE TITLE
[enterprise-3.11] Edit suggested in file upgrading/automated_upgrades.adoc

### ISSUE THREAD

**Issue by chuckersjp** [openshift/openshift-docs#21638]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/upgrading/automated_upgrades.html#upgrading-efk-logging-stack

### What needs fixing?

Previously, this section contained the following:
```
If your Fluentd DeploymentConfig and DaemonSet for the EFK components are already set with: 

image: <image_name>:<vX.Y>         
imagePullPolicy: IfNotPresent    

The latest version <image_name> might not be pulled if there is already one with the same 
<image_name:vX.Y> stored locally on the node where the pod is being re-deployed. If so, manually 
change the DeploymentConfig and DaemonSet to imagePullPolicy: Always to make sure it is re-pulled.

```
(Compare with https://docs.openshift.com/container-platform/3.10/upgrading/automated_upgrades.html#upgrading-efk-logging-stack)
This section is no longer present and is actually an important step in the upgrade process.

**Comment by mburke5678** [comment]
@rolfedh Not sure what happened here. 

The intro sentence and code block was removed here, no reason why I removed them:
https://github.com/openshift/openshift-docs/pull/17931/files#diff-20aef49252d49e01d0111069c7458fe548450c7a5461bb5ffe7ad8bde4ff47a7L759

The paragraph after the code block seems to have disappeared, not sure where. 
The paragraph is in this PR:
_moving ifdef_
kalexand-rh authored and openshift-cherrypick-robot committed on Sep 28, 2018
https://github.com/openshift/openshift-docs/commit/a7b39c5bc017ce86cd763cb2c375d726b7b4d62b#diff-20aef49252d49e01d0111069c7458fe548450c7a5461bb5ffe7ad8bde4ff47a7

The paragraph is not here in the next PR:
_3.11 upgrade updates_
kalexand-rh committed on Oct 1, 2018
https://github.com/openshift/openshift-docs/commit/41efb0a019a788bc63292eeb7c082f55ed185cf5#diff-20aef49252d49e01d0111069c7458fe548450c7a5461bb5ffe7ad8bde4ff47a7

**Comment by mburke5678** [comment]
@chuckersjp Thank you for pointing this out. I reached out to our OpenShift Logging QE resource and he agreed that the information should be in the 3.11 docs. However, he suggested, instead of updating the Deployment Config or Daemonset, to update the Ansible variables, seeting `openshift_image_tag=v3.11.<Z>` or 
`oreg_url=registry.access.redhat.com/openshift3/ose-${component}:v3.11.<Z>`, as the upgrade overwrites the image version in the DC and DS. Can you take a look and let me know what you think?

https://github.com/openshift/openshift-docs/pull/30755/files#diff-20aef49252d49e01d0111069c7458fe548450c7a5461bb5ffe7ad8bde4ff47a7L867-R891

**Comment by chuckersjp** [comment]
I think that might work but I am not 100% positive.  I do know I have been bitten by no having `imagePullPolicy: Always` on it but that could be a side effect of perhaps not including the <Z> in the image tag.

It might be helpful to include both statements.  But at a bare minimum it does need to be back in the docs in some fashion.

**Comment by mburke5678** [comment]
PR is merged. Closing.
