### ISSUE TITLE
[enterprise-4.4] Edit suggested in file machine_management/more-rhel-compute.adoc

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/openshift-docs#21881]
### Which section(s) is the issue in?
About adding RHEL compute nodes to a cluster

### What needs fixing?
According to @katherinedube RHEL workers can be added regardless whether the cluster was created with user-provisioned infrastructure or installer-provisioned infrastructure.

**Comment by katherinedube** [comment]
@sdodson I know we already resolved allowing RHEL 7 server workers to be added to an installer-provisioned cluster (since there isn't any differences between the install methods from a day 2 operational perspective), but do you know if there was ever a BZ or PR opened to track making updates to the product documentation? I thought something was already submitted for this. Otherwise, I know we cover this use case already as part of the QE test matrix. Thanks!
