### ISSUE TITLE
[OSP] Add information about etcd disk requirements

### ISSUE THREAD

**Issue by maxwelldb** [openshift/openshift-docs#22552]
### Which section(s) is the issue in?

OSP requirements docs.

### What needs fixing?

https://github.com/openshift/installer/pull/3669/files

**Comment by maxwelldb** [comment]
@pierreprinetti Is this scoped to any particular version or is this general guidance?

**Comment by pierreprinetti** [comment]
>Is this scoped to any particular version

Both the advice ("run on fast disks") and the number (10ms latency at the 99th percentile for fdatasync) are valid for all versions of OpenShift, because they depend on ETCD requirements which have AFAIK never changed.

By the way, the advice is valid for all platforms (it is not OpenStack-specific), even though it might make little sense in branded clouds like AWS, OCP or Azure.

**Comment by maxwelldb** [comment]
Tracking in https://issues.redhat.com/browse/OSDOCS-4530
