### ISSUE TITLE
Remove use of obviously offensive language

### ISSUE THREAD

**Issue by rmkraus** [openshift/openshift-docs#22854]
### Which section(s) is the issue in?
all sections

### What needs fixing?
Currently, there are 76,758 lines containing the word master. There are some places where, for the sake of clear documentation, the word master should be used as it is still a Kubernetes term and appears in Kubernetes output. In many occurrences, it could be accurately replaced by the words "control plane" which would be more descriptive and less offensive. 

Currently, there are 3108 lines containing the word slave. Slave is not a Kubernetes word, but it does appear in nmcli commands. Other uses of the word slave appear in reference to MySQL server configurations and Jenkins server configurations. In these two instances, a less offensive word could likely be used that would not introduce confusion.

There are 3953 lines containing the word whitelist. Many uses are colloquial and not in reference to a technology protocol or configuration these should be changed to be more descriptive and less offensive. Some uses are in reference to protocols (like LDAP), these may be harder to change and remain clear. Many of the uses are in reference to firewall configurations where the term can be deprecated without causing confusion.

There are 2940 lines containing the word blacklist. See above for comments.

What is the appetite for changing this? I'd be happy to start contributing to this on the side, although, I'd never be able to tackle this all myself. I also think it would be great to implement a CI check that checks for occurrences of these words and flags them.

**Comment by blacklistisnotracist** [comment]
@rmkraus Would you mind explaining why those terms are offensive? As for whitelist/blacklist, they don't have any racist connotations so if you're talking about racist then that's automatically wrong.

**Comment by rmkraus** [comment]
I think most of your concern is regarding blacklist/whitelist. Those are terms that date back to the 17th century and were not rooted in racism. However, it is important to note that language evolves and nobody here was alive in the 17th century. In the 13th century, the word awful used to mean wonderful and full of awe. That is no longer the case because language has evolved. In this century, it is no longer appropriate to continue associating the word black with bad. 

At best, the words are non-descriptive and unclear to non-English speakers. At worst, they pile on to the death of a thousand papercuts that reinforces the racial bias of our industry. All of us should be constantly striving to evolve and try to understand the experience of others. Replacing these words with more descriptive words not only makes our software better, but it also is a small step towards making more people comfortable in our industry.

**Comment by rmkraus** [comment]
For additional resources demonstrating that this change in industry is necessary, relevant, and happening:

- https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.2
- https://developers.google.com/style/word-list#blacklist (for good examples of handling this in documentation)
- https://lethargy.org/~jesus/writes/a-guide-to-nomenclature-selection/ (good read if you disagree)

**Comment by blacklistisnotracist** [comment]
> That is no longer the case because language has evolved.

As far as I can see, most of those who claim blacklist/whitelist to carry racist connotations are actually white American people. Even among white American people, it is hard to say that the majority would agree that blacklist/whitelist have anything to do with racism. This entire movement seems to be just trying to give these offensive meanings to innocent words.

> it is no longer appropriate to continue associating the word black with bad.

This is not a strong argument because the color black has nothing to do with black people. Black color has association with darkness/night and, since we humans are diurnal creatures, we fear darkness. Even the primitives used black for scary subjects. This is so embedded in our nature that we see many instances of the association of the color black with something negative/scary across many languages and many cultures. Black=bad has nothing to do with race. It would make more sense if we stop using black to address black people. Nobody would think of black people when we're using words that have black in them. For example, black magic has nothing to do with black people. Blackbox doesn't mean it's a box of black people.

> For additional resources demonstrating that this change in industry is necessary, relevant, and happening:
> - https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.2
> - https://developers.google.com/style/word-list#blacklist (for good examples of handling this in documentation)
> - https://lethargy.org/~jesus/writes/a-guide-to-nomenclature-selection/ (good read if you disagree)

Thanks for sharing these references. However, respectfully, just because some people want to ban the word, it doesn't always mean that we should be doing the same. We should not die on authoritarianism.

Lastly, I'd like to mention that I'm not against the changes of blacklist/whitelist to some clearer alternatives. I just wanted to point out that blacklist/whitelist are not offensive.

**Comment by rmkraus** [comment]
Thank you for your concerns and polite discord. Racial discussions are certainly complex, nuanced, and difficult.

1. You are probably correct, although we have to be careful not to fall victim to observation bias. That is what it means to be considerate. It is necessary for all people to inconvenience themselves, to a degree, in order to make other feel more comfortable. Sometimes we may over correct, we will always be behind, but being considerate is a journey, not a destination.

2. I am an American. As such I cannot speak in an educated way as to how these terms resonate in other cultures. However, replacing these words with more descriptive words would certainly make them easier for non-English speakers to understand. I mean, DenyList is certainly more contextually accurate than BlackList. I know that there are some Black people that are offended by these words. Changing these words to more descriptive words increases the quality of our software and, at the very least, makes our software more inclusive to (at least) some of a group of people that have been systematically distanced.

3. Could you please provide (non-anecdotal) evidence that in modern linguistics the term Black is associated with the lack of light before race? The two of us do not get to be the gatekeepers of linguistics. If I could file a PR against the English language, I would. Would that make more sense? Maybe. But, alas, here we are. We have to be observant of those around us and be considerate of how they may feel. That's the only way for Open Source to work. I can't change the English language, but I can change open source documentation. Also, could you provide (non-anecdotal) evidence for: "Nobody would think of black people when we're using words that have black in them."?

4. Absolutely. Don't follow a crowd for the sake of following a crowd. However, sometimes when a crowd of people are doing something, it is not authoritarianism. Sometimes its just a honkin' good idea. In order to be authoritarianism, there must be a central authority enforcing the behavior. There isn't one here.

5. I would like to point out that simply because a word is not offensive to you, does not mean it is not offensive. Neither of us gets to decide the conscious and non-conscious reactions our friends and colleagues have to certain words. Unfortunately, people are complex beings. This is a small step we can take to be more considerate towards (at least) a portion of a group of people that deserve more than inclusion, they deserve equality.

Finally, what is your goal here? I'm not sure I understand. It seems that you agree with me that change should be made, even if you disagree on the reasoning. The point of an Issue on GitHub is to point to something that should change and provide (at least) on reason why. You have agreed and provided a second reason why this should be changed. Since we are in agreement on the crux of the issue (that there are better words to use), what are you working towards? I'm not sure what you are asking from me. If you just want to have a constructive conversation about the Black experience in America, asking questions of a mustachioed White guy on GitHub hardly seems to be the most productive way of doing that.

**Comment by blacklistisnotracist** [comment]
> You are probably correct, although we have to be careful not to fall victim to observation bias. That is what it means to be considerate. It is necessary for all people to inconvenience themselves, to a degree, in order to make other feel more comfortable. Sometimes we may over correct, we will always be behind, but being considerate is a journey, not a destination.

If you use this logic, this can go too far. It's simply a not good idea. Ok, for example, we should not be using red color for displaying error messages because it could be offensive for Native Americans. Also words like "atomic" could be very offensive for Japanese people since US dropped two atomic bombs on their soil.

> I am an American. As such I cannot speak in an educated way as to how these terms resonate in other cultures. However, replacing these words with more descriptive words would certainly make them easier for non-English speakers to understand. I mean, DenyList is certainly more contextually accurate than BlackList. I know that there are some Black people that are offended by these words. Changing these words to more descriptive words increases the quality of our software and, at the very least, makes our software more inclusive to (at least) some of a group of people that have been systematically distanced.

Agreed. No mentioning of potential offensiveness was needed.

> Could you please provide (non-anecdotal) evidence that in modern linguistics the term Black is associated with the lack of light before race? The two of us do not get to be the gatekeepers of linguistics. If I could file a PR against the English language, I would. Would that make more sense? Maybe. But, alas, here we are. We have to be observant of those around us and be considerate of how they may feel. That's the only way for Open Source to work. I can't change the English language, but I can change open source documentation. 

Black color is associated with the lack of light is more than obvious. You can turn off your light in your room to confirm that. 

> It is often used symbolically or figuratively to represent darkness, while white represents light.
https://en.wikipedia.org/wiki/Black

I don't think Wikipedia might be the best reference, but you can do your research from its reference list.

> Also, could you provide (non-anecdotal) evidence for: "Nobody would think of black people when we're using words that have black in them."?

I don't have a toll here. But the fact that the government or any publishers haven't banned the word is enough reason for this not to be called a racist term.

> Absolutely. Don't follow a crowd for the sake of following a crowd. However, sometimes when a crowd of people are doing something, it is not authoritarianism. Sometimes its just a honkin' good idea. In order to be authoritarianism, there must be a central authority enforcing the behavior. There isn't one here.

Well, I didn't use authoritarianism to mean that. I hope you could understand what I was trying to say. Authority worship? I don't know the exact word but I'm trying to say following the crowd doesn't mean it's right. I'm glad that you got what I was trying to say. Thanks.

> I would like to point out that simply because a word is not offensive to you, does not mean it is not offensive. Neither of us gets to decide the conscious and non-conscious reactions our friends and colleagues have to certain words. Unfortunately, people are complex beings. This is a small step we can take to be more considerate towards (at least) a portion of a group of people that deserve more than inclusion, they deserve equality.

Every word is offensive to someone. It's an endless adventure. The history has proven that. Just because you ban a word, the problem will never go away.

> Finally, what is your goal here? I'm not sure I understand. It seems that you agree with me that change should be made, even if you disagree on the reasoning. The point of an Issue on GitHub is to point to something that should change and provide (at least) on reason why. You have agreed and provided a second reason why this should be changed. Since we are in agreement on the crux of the issue (that there are better words to use), what are you working towards? I'm not sure what you are asking from me. If you just want to have a constructive conversation about the Black experience in America, asking questions of a mustachioed White guy on GitHub hardly seems to be the most productive way of doing that.

My goal here is to stop people from spreading the wrong meaning of the terms. When you ban a word just because it's negative and it has black in it, it could give others a sense of guilt when they use ANY negative words that have black in it even though they don't mean to sound like a racist. This is ridiculous and this is definitely NOT the world that I would want to live in. If you go to the super extreme, every horror movie now should not be black. Every villain should not were black clothes. Please, please don't reinforce this wrong sense of the usage of this color.

My request for you would be to remove the mentioning of "offensive" or "potential racist connotations" in blacklist/whitelist. Because that's simply wrong and language matters to me. I would really appreciate it if we could agree on this. Thanks.

**Comment by rmkraus** [comment]
> Well, I didn't use authoritarianism to mean that. 

Understood. Please be careful choosing words. Authoritarianism is another word that has a strong emotional reaction by many, like black. I'm glad you understand that words can elicit emotional responses that were not always intended by the speaker.

> Every word is offensive to someone. It's an endless adventure. 

Again, that is a great definition of being consideration and kindness. It is an endless adventure. But it is an adventure that is absolutely worth perusing.

> My goal here is to stop people from spreading the wrong meaning of the terms.

Like I said, we do not get to decide on the linguistic ramifications of words. I wish we could. That would be far simpler. If you want to engage in a dialog of linguistics, might I suggest a different venue?

> My request for you would be to remove the mentioning of "offensive" or "potential racist connotations" in blacklist/whitelist. Because that's simply wrong and language matters to me. I would really appreciate it if we could agree on this. Thanks.

We agree again! Language absolutely matters. Offensive is the correct term. [See the definition here.](https://www.dictionary.com/browse/offensive) These words DO cause resentful displeasure to some. Not me. Not you. But to a great many. 

As for the latter, my issue does not mention racism. That was really you're thing. Race was not discussed until you got here. So again, I'm not sure what you are asking me.

**Comment by blacklistisnotracist** [comment]
> Like I said, we do not get to decide on the linguistic ramifications of words. I wish we could. That would be far simpler. If you want to engage in a dialog of linguistics, might I suggest a different venue?

If you want to contribute to making these words offensive words, then what you're doing is a great contribution to your goal.

> These words DO cause resentful displeasure to some.  ... But to a great many.

Would you mind providing any proof for this?

> As for the latter, my issue does not mention racism. That was really you're thing. Race was not discussed until you got here. So again, I'm not sure what you are asking me.

Is it a coincidence that you brought up blacklist/whitelist in this BlackLivesMatter time?

**Comment by rmkraus** [comment]
> If you want to contribute to making these words offensive words, then what you're doing is a great contribution to your goal.

I certainly do not want to do that. But to ignore that it is a troubling use of terminology to many is just blinding yourself to the world you live in. I am not making the word offensive, it is already offensive to many.

> Would you mind providing any proof for this?

There are so many. Here are a few.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6148600/
https://www.youtube.com/watch?v=ueDbCmG3iu4
https://www.scientificamerican.com/article/the-bad-is-black-effect/
Written by a black man: http://www.stlamerican.com/news/editorials/why-is-black-always-a-bad-word/article_9fdf3fd1-a263-536a-8b11-a80d4dcfe0b1.html

> Is it a coincidence that you brought up blacklist/whitelist in this BlackLivesMatter time?

The Black Lives Matter movement started in 2013. So that's not new. Are you specifically refering the murder of George Floyd? Is your ask that I not strive for a less offensive world around the time a Black man is murdered by the police? If so, there would never be an appropriate time to raise this issue.

Might I suggest that, if you cannot articulate a request that I have not either fully complied with or reasonably responded to, then maybe your frustration isn't with me or this GitHub Issue.

**Comment by blacklistisnotracist** [comment]
Your point seems to be solely based on "black" having negative connotations. In that case, you can't fix it. Because we humans are diurnal animals thus we fear darkness. Wouldn't it make more sense if we stop calling a certain group of people "Black"? It's much faster and easier. Why do you want to keep labeling them as black?

> https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6148600/

What are you trying to say with this paper? It has been cited [only four times](https://scholar.google.com/scholar?cites=17419557131221922597&as_sdt=2005&sciodt=0,5&hl=en), which suggests that the argument of this paper does not represent the academic view of these terms. If you have gone through any academic training, I bet you can understand what I'm saying.

>  Are you specifically refering the murder of George Floyd?

Yes. This implies that you think blacklist is offensive for black people.

**Comment by rmkraus** [comment]
My point is that some people find those words (in particular) offensive and that is grounds enough for their removal. You didn't dispute that. You agreed that whitelist/blacklist are not the best terms, albeit on a different premise. 

Might I suggest that, if you cannot articulate a request that I have not either fully complied with or reasonably responded to, then maybe your frustration isn't with me or this GitHub Issue.

**Comment by blacklistisnotracist** [comment]
What is the suggested word as an alternative of blacklist? I'm pretty sure your alternative would also offend some people.

My points are:

- Blacklist is not considered to be an offensive word in the general public. There's a TV series called ["The Blacklist"](https://en.wikipedia.org/wiki/The_Blacklist_(TV_series)).
- Calling such an innocent word carrying racist connotations or potentially offensive is simply giving false impression to other people outside of out community. This will lead to the entire corruption of our language and culture.
- No evidence of how many people are suffering from these terms. Hence no necessity of changing the terms.

**Comment by rmkraus** [comment]
The standard alternatives, which are dependent on context, are AllowList and DenyList. Again, just because the word doesn't offend you, don't mean that it doesn't offend others.

I think we may have reached the end of what we can achieve in this forum and we are both getting quite repetitive. I appreciate you sharing your opinions. I have also shared mine. I feel as if I was heard. I hope you feel the same. I hope that I have not offended you. I apologize if I have. I have not been offended. 

At this point, it will be up to the maintainers of the project (Red Hat) to make a decision on this matter.

**Comment by blacklistisnotracist** [comment]
AllowList and DenyList will also offend some people. For example, what about people who have faced denial from someone who they care. Seeing this term would remind them of their bad memories of being denied by people they cared.

My point here is, "some people might be offended" is simply a bad argument to make some words offensive words. Unless it's commonly agreed that "blacklist" is an offensive word used against black people, calling blacklist an offensive word is merely a nonsense hypocrite act. Have you looked up the word in a dictionary?

**Comment by gaurav-nelson** [comment]
This one should get some :eyes:
