### ISSUE TITLE
[enterprise-4.4] Include post-install docs for Registry on RHV and OpenStack

### ISSUE THREAD

**Issue by davivcgarcia** [openshift/openshift-docs#23558]
### Which section(s) is the issue in?

The docs are mentioning that IPI-based installs don't require configuring Registry manually, but that's not true in newer versions. For example, IPI for RHV and RHOSP does require manual configuration of Registry storage after install.

Also, there aren't sessions about what configurations should be done for RHV and OpenStack, like there is bare-metal or vSphere for example.

### What needs fixing?

The text `Storage is only automatically configured when you install an installer-provisioned infrastructure cluster on AWS, GCP, Azure, or OpenStack.` should not include OpenStack.

New sessions should be added for OpenStack and RHV, such as:

- Setting up and configuring the registry
   - Configuring the registry for OpenStack
   - Configuring the registry for RHV

**Comment by bmcelvee** [comment]
@davivcgarcia thank you for pointing this out. Since this is a larger RFE, I opened an issue on the OSDOC Jira board to track this work: https://issues.redhat.com/browse/OSDOCS-1536. 

Since it will be tracked elsewhere, I am going to go ahead and close this issue. Please let me know if you have any questions. Thanks again!
