### ISSUE TITLE
[enterprise-4.5] Issue in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by npoyant** [openshift/openshift-docs#24119]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/installing/installing_vsphere/installing-vsphere-network-customizations.html#installation-vsphere-machines_installing-vsphere-network-customizations

Step 5, sub-step d:   It references "...The folder name must match the cluster name that you specified in the install-config.yaml file.",  what it does not mention is that after the cluster is up, that a auto generated hash is appended to the cluster name inside of OCP and that does not match the folder structure.  This impacts the ability to dynamically create storage as it's looking for a folder that does exist.  Another step would need to be noted to state as a post config step, change the folder name to match the new cluster name is required.

**Comment by kalexand-rh** [comment]
This procedure has been updated so that you [obtain](https://docs.openshift.com/container-platform/4.5/installing/installing_vsphere/installing-vsphere.html#installation-extracting-infraid_installing-vsphere) and use the infrastructure ID, which contains that auto generated hash, up front. That step now says to "... create a folder with the same name as the infrastructure ID."

I'm closing this issue, but please reopen it with more context if you're still seeing this issue.
