### ISSUE TITLE
[enterprise-4.5] Issue in file nodes/nodes/nodes-nodes-working.adoc - oc adm delete node is wrong

### ISSUE THREAD

**Issue by ptrnull** [openshift/openshift-docs#25309]
### Which section(s) is the issue in?
Deleting nodes from a bare metal cluster

### What needs fixing?
The command "oc adm delete node <node_name>" doesn't exists and gives an error:

$ oc adm delete node worker-1.mycluster
error: unknown command "delete node worker-1.mycluster"

The right command is "oc delete node <node_name>", for example:
$ oc delete node worker-1.mycluster
node "worker-1..mycluster" deleted

**Comment by codyhoag** [comment]
@sunilcio using the `oc adm` command to delete nodes was recommended in [BZ#1846520](https://bugzilla.redhat.com/show_bug.cgi?id=1846520). I see that `delete` is considered a Developer command [here](https://docs.openshift.com/container-platform/4.5/cli_reference/openshift_cli/developer-cli-commands.html#delete), instead of being listed as an admin command [here](https://docs.openshift.com/container-platform/4.5/cli_reference/openshift_cli/administrator-cli-commands.html).

Can you confirm the removal of `adm` for deleting nodes:

```
oc delete node <node_name>
```

**Comment by sunilcio** [comment]
@codyhoag yes, correct. It should be `oc delete node <node_name>`. Thanks for correcting.
