### ISSUE TITLE
[enterprise-4.5] Issue in file serverless/serverless-release-notes.adoc

### ISSUE THREAD

**Issue by werkins** [openshift/openshift-docs#25581]
### Which section(s) is the issue in?
Introduction

### What needs fixing?
There is a note saying Openshift Serverless is still in Tech Preview; however, it was announced some months ago that it went GA: https://www.openshift.com/blog/openshift-serverless-now-ga

**Comment by jboxman** [comment]
@abrennan89 FYI

**Comment by abrennan89** [comment]
@werkins can you please provide a link to where you are seeing this note?
There is still a note specifically for the Knative Eventing component here: https://docs.openshift.com/container-platform/4.5/serverless/serverless-getting-started.html#serverless-getting-started-supported-configs

which is still valid since only Knative Serving is GA, Eventing is still Technology Preview.

**Comment by abrennan89** [comment]
@werkins @jboxman 
I think the note you mean is here: https://docs.openshift.com/container-platform/4.5/serverless/serverless-release-notes.html

but this note is specific to the Knative Eventing component, it does not say that Openshift Serverless is still in Tech Preview.
Knative Serving is GA, but the Knative Eventing component remains Tech Preview until later this year.

Hopefully this helps.

**Comment by werkins** [comment]
@abrennan89 You're right, sorry about the confusion

**Comment by abrennan89** [comment]
@jboxman could you close this one please?
