### ISSUE TITLE
broken link in the developers_console/cli page for xPaas link

### ISSUE THREAD

**Issue by jmtd** [openshift/openshift-docs#2577]
page openshift-docs/getting_started/developers_cli.adoc

context:

In addition, JBoss Middleware has put together a broad range of {product-title} templates as well as xref:../using_images/xpaas_images/index.adoc#using-images-xpaas-images-index[images] as part of their xPaaS services.

that xref does not work

live example

https://docs.openshift.org/latest/getting_started/developers_console.html#getting-started-developers-console

broken link

https://docs.openshift.org/latest/using_images/xpaas_images/index.html#using-images-xpaas-images-index

**Comment by adellape** [comment]
Pretty sure that xPaaS content is only supposed to be visible in the downstream distros (i.e., Enterprise and Dedicated docs), since the images come from registry.access.redhat.com. Fixed via https://github.com/openshift/openshift-docs/pull/2580 and republished Origin docs.

@vikram-redhat If we need to replace this w/ anything for Origin, please LMK.

**Comment by adellape** [comment]
Thanks for reporting, @jmtd :+1:
