### ISSUE TITLE
Documentation for mirroring OKD image repository instructs mirroring of OCP

### ISSUE THREAD

**Issue by B-Simms** [openshift/openshift-docs#27053]
### Which section(s) is the issue in?
[OKD Latest > Installing > Installation configuration > Creating a mirror reigstry for a restricted network](https://docs.okd.io/latest/installing/install_config/installing-restricted-networks-preparations.html#installing-restricted-networks-preparations)

### What needs fixing?
The instructions and code snippets point the user to `ocp-release` but this is describing mirroring the OKD image repository and I believe should it should point them to a different repository. 

Specifically, in part 2. of the Section "Mirroring the OKD image repository", the instructions describe setting the environment variables `OCP_RELEASE=<release_version>`, `PRODUCT_REPO='openshift-release-dev'` and `RELEASE_NAME="ocp-release"`

I believe these should be pointing to `openshift/okd-content`.

**Comment by vrutkovs** [comment]
All OKD builds are amd64, so `-${ARCHITECTURE}` needs to be removed as well

**Comment by B-Simms** [comment]
@vrutkovs 
Shouldn't `PRODUCT_REPO` be `openshift` and `RELEASE_NAME` be `okd`?

Also, isn't the `quay.io` repo `openshift/okd-content`? Maybe I'm misunderstanding how the mirror finds those images. I'm pretty new to this tech.

**Comment by vrutkovs** [comment]
>Shouldn't PRODUCT_REPO be openshift and RELEASE_NAME be okd?

You're correct, edited my comment

> Also, isn't the quay.io repo openshift/okd-content? Maybe I'm misunderstanding how the mirror finds those images. I'm pretty new to this tech.

There are two repos involved here: `okd` and `okd-content`.
`okd-content` has actual images used by OKD - cluster operators, prometheus, machine-os-content etc. Every release is referencing a particular image from `okd-content` repo by digest. However, these are useless without a so-called "release payload" (an operator which spins up other operators), which is stored in `okd`.
When the release is mirrored its necessary to point it to a particular release payload - i.e. `quay.io/openshift/okd:4.5.0-0.okd-2020-10-15-235428`. `oc adm release` parses this image and fetches necessary images from quay.io/openshift/okd-content (or any other locations).
These images are stored in different repositories because this is what OCP does - release payloads can be downloaded freely and actual content requires a pull secret. This difference doesn't make much sense in OKD but its historical I guess

**Comment by B-Simms** [comment]
This makes sense and perfectly cleared up some confusion I was having. Thanks very much for that.

**Comment by vikram-redhat** [comment]
@vrutkovs is there a follow up here? Or is this ok to close?

**Comment by vrutkovs** [comment]
This needs to be a open - mirroring details are different for OKD

**Comment by bergerhoffer** [comment]
@vrutkovs @B-Simms Can you please take a look at PR #30930 and make sure that my updates are correct? Here's a summary of the changes for OKD:

* `PRODUCT_REPO='openshift'`
* `RELEASE_NAME="okd"`
* For the above steps, I also removed two lines that said "For a production release, you must specify..." - but let me know if we still need those for OKD, with the above values.
* Removed setting `ARCHITECTURE`

Previews:
* OKD (internal): http://file.rdu.redhat.com/~ahoffer/2021/github-27053/installing/install_config/installing-restricted-networks-preparations.html#installation-mirror-repository_installing-restricted-networks-preparations
* OCP: https://deploy-preview-30930--osdocs.netlify.app/openshift-enterprise/latest/installing/install_config/installing-restricted-networks-preparations.html#installation-mirror-repository_installing-restricted-networks-preparations

**Comment by bergerhoffer** [comment]
Updates are live: https://docs.okd.io/latest/installing/install_config/installing-restricted-networks-preparations.html#installation-mirror-repository_installing-restricted-networks-preparations
