### ISSUE TITLE
Cross-link between OpenShift Origin and OpenShift Enterprise/OpenShift Container Platform documentation

### ISSUE THREAD

**Issue by jawnsy** [openshift/openshift-docs#2812]
Most of the documentation is equivalent between OpenShift Origin and OpenShift Enterprise, but because the documentation pages look very similar, it can be difficult to determine whether the documentation you're reading is applicable to the product you're using.

For example, compare: https://docs.openshift.com/enterprise/latest/creating_images/guidelines.html and https://docs.openshift.org/latest/creating_images/guidelines.html

It would be nice to have some easy indication of the product to which the currently-viewed documentation applies, for example a banner notice at the top stating: "This documentation applies to OpenShift Origin. [View the documentation for OpenShift Enterprise instead.](http://docs.openshift.org)" - the cross-link is helpful particularly if you find the documentation via a search engine and want to make sure that everything in the document applies to your product. Unfortunately, there's also similar problems between versions of the same product as well (it's possible to be reading documentation for 3.2 only to find that the feature doesn't exist in 3.1, which is useful information though could be frustrating for users).

Other ideas might be:
- A drop-down link in place of the "OpenShift Origin Latest" text in the breadcrumb (this would require knowing whether a document of the same name exists in other products)
- More distinguished logos in the header (currently OpenShift Online and OpenShift Enterprise share the same logo)
- A built-in search function that users can use in place of Google, so that users can easily narrow down their searches to a single product

Unfortunately, this might be tricky to implement since each set of documentation may be built separately, making each build dependent on other builds :/

**Comment by bfallonf** [comment]
@jawnsy Thanks!

@nhr This seems more like feedback appropriate for you. Can I assign this to you and let you look it over?

**Comment by nhr** [comment]
Two potential pitfalls:

1. We have six distro/branch combos (Origin, OCP 3.1-3.3, Dedicated 3.2, Online) - so do we provide links to all of them? I could see an argument for shimming a select list into the breadcrumb nav that runs across the top of each page, so that where it says the distro/branch name now we could instead have a pick list. However...

2. This assumes 100% page parity between distro/branch docs sets, which is not guaranteed. So what do we do when someone tries to change context and ends up at a 404? We can make the server handle this gracefully but the experience may be confusing.

**Comment by mburke5678** [comment]
@bfallonf Did anything come of this?

**Comment by vikram-redhat** [comment]
Closing this as there are no plans to do this at the moment.
