### ISSUE TITLE
[enterprise-4.3] Issue in file service_mesh/v1x/preparing-ossm-installation.adoc

### ISSUE THREAD

**Issue by danielmenezesbr** [openshift/openshift-docs#28601]
### Which section(s) is the issue in?
All.

### What needs fixing?
The page "Preparing to install Red Hat OpenShift Service Mesh" (https://docs.openshift.com/container-platform/4.3/service_mesh/v1x/preparing-ossm-installation.html) is not accessible on 4.3.

**Comment by bergerhoffer** [comment]
FYI @JStickler and @vikram-redhat 

It looks like all service mesh docs on 4.3 are attempting to redirect to a path with "v1x" in it, even though the v1x/v2x separation wasn't done until 4.4+. I realize that 4.3 is out of support, but perhaps this is a bad set of redirects that could be undone?

**Comment by JStickler** [comment]
@bergerhoffer I'd rather not make updates to versions that are out of support, since our engineering team does not want to encourage installations on older releases.    Could we close this one as "Won't Fix" ?

**Comment by bergerhoffer** [comment]
Yeah normally I wouldn't recommend updating 4.3 content since it's out of support, but this looks like it might have been redirects that were set up for 4.3 when they shouldn't have been. It's making the whole 4.3 doc set for service mesh 404, which is never a good look for our docs. And it might be a simple matter of undoing redirects for 4.3, so it could be worthwhile to look into. But I don't know if that's a simple or complex change. So I'd leave it up to @vikram-redhat to either see if it's easy or close as won't fix.
