### ISSUE TITLE
[enterprise-4.6] Issue in file networking/ingress-operator.adoc

### ISSUE THREAD

**Issue by lautou** [openshift/openshift-docs#28781]
### Which section(s) is the issue in?

Setting a custom default certificate

### What needs fixing?

"Your certificate is valid for the Ingress domain."
This explanation is not complete you must precise:
"The certificate must have a subjectAltName extension of *.apps.<OPENSHIFT-DOMAIN>, such as *.apps.ocp4.example.com, that enables using the certificate as a wildcard certificate for the .apps subdomain."

**Comment by jboxman** [comment]
Making some progress.

> Miciah Dashiel Butler Masters  8 days ago
I think OpenShift is fine with either CN or SAN, but IIRC people are moving towards always using SAN and largely ignoring CN.
Also, I'm not sure that the SAN/CN absolutely needs to be a wildcard (as opposed to listing out each route host as a SAN), but it's definitely a good idea.  But I'd have thought the requirement that the certificate be "valid" would be clear enough.

> Miciah Dashiel Butler Masters  8 days ago
Hm, yeah, looks like putting the host name as the common name was never intended and is being deprecated:  https://unmitigatedrisk.com/?p=381
So recommending putting the wildcard domain as the SAN (or possibly listing as a SAN the host of each route that uses the wildcard domain) makes sense.  I'll check whether listing host names instead of using a wildcard actually works and get back to you.  (Although even if it works, I wonder if we really want to document it as supported...  but we do have customers who cannot or would rather not use wildcards, so I've been meaning to investigate whether listing host names works.)

**Comment by lautou** [comment]
Any update?

**Comment by lautou** [comment]
Hi any update?

**Comment by jboxman** [comment]
@lautou, this is fixed now, thanks!
