### ISSUE TITLE
[enterprise-4.6] Issue in file support/gathering-cluster-data.adoc

### ISSUE THREAD

**Issue by crombus** [openshift/openshift-docs#28906]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/support/gathering-cluster-data.html#gathering-data-specific-features_gathering-cluster-data

registry.redhat.io/ocs4/ocs-must-gather-rhel8 | Data collection for Red Hat OpenShift Container Storage.
-- | --

### What needs fixing?

registry.redhat.io/ocs4/ocs-must-gather-rhel8:v4.6 | Data collection for Red Hat OpenShift Container Storage.
-- | --

**Comment by bergerhoffer** [comment]
It looks like this has been fixed in 4.6 with #28917 / https://bugzilla.redhat.com/show_bug.cgi?id=1921544. But 4.7 [1] was not  updated to have a version specified.

@sagidlow Did you ever find out whether the image in the 4.7 docs needs to be updated to `registry.redhat.io/ocs4/ocs-must-gather-rhel8:v4.7`? @zhouying7780 do you know?

[1] https://docs.openshift.com/container-platform/4.7/support/gathering-cluster-data.html#gathering-data-specific-features_gathering-cluster-data

**Comment by sagidlow** [comment]
@bergerhoffer - I asked the QE but they never said anything about update to 4.7. Let me reach back out to him and double check regarding 4.7.

**Comment by zhouying7780** [comment]
@sagidlow @bergerhoffer  I agree with we also update to 4.7 .
