### ISSUE TITLE
okd.io latest empty search

### ISSUE THREAD

**Issue by biau** [openshift/openshift-docs#28979]
### Which section(s) is the issue in?
https://docs.okd.io/latest/welcome/index.html

### What needs fixing?
Search box does not return any results

**Comment by vikram-redhat** [comment]
@jiri-fiala could you take a look?

**Comment by jiri-fiala** [comment]
Hi @vikram-redhat,

This is caused by the version variable (`4`) and actual URL path (`/latest/`) discrepancy that is specific to the OKD v4 latest docs; the search is filtered by a string that is never in the search index. I submitted #29098 that is supposed to work around this situation, but it is also something to keep in mind in case of further changes in the version/URL logic.

Please have a look (I believe it needs to be cherry picked from the OCP 4.1 docs branch at least).

Thanks.

**Comment by biau** [comment]
It looks like the problem is back

**Comment by jiri-fiala** [comment]
The problem is caused by the search backend itself this time, affects all the OKD docs versions and does not require any fix in docs' codebase. It should be fixed within an hour.
