### ISSUE TITLE
[enterprise-4.5] Issue in file nodes/scheduling/nodes-scheduler-taints-tolerations.adoc

### ISSUE THREAD

**Issue by esimim** [openshift/openshift-docs#29460]
### Which section(s) is the issue in?
Here, if this pod is running but does not have a matching taint, the pod stays bound to the node for 3,600 seconds and then be evicted. If the taint is removed before that time, the pod is not evicted.

### What needs fixing?
Here, if this pod is running and it does have a matching taint, the pod stays bound to the node for 3,600 seconds and then be evicted. If the taint is removed before that time, the pod is not evicted.

**Comment by mburke5678** [comment]
@esimim Thanks for this issue. Taints and tolerations have confused me since I started at Red Hat! I think it should say _Here, if this pod is running and it does have a matching **toleration**, the pod stays bound..._ 

If the pod doesn't have a matching toleration, the NoExecute parameter it gets removed.

The point of the text is to demonstrate the tolerationSeconds parameter and that it delays removing pods for that duration. We want to have an example where the pod would be removed. 

Am I correct here?

**Comment by mburke5678** [comment]
PR for changing taint to toleration: https://github.com/openshift/openshift-docs/pull/30359

**Comment by mburke5678** [comment]
@esimim   Closing this issue as fixed. Please let me know if this doesn't address your concerns.
