### ISSUE TITLE
[dedicated] Issue in file welcome/index.adoc

### ISSUE THREAD

**Issue by jdbenson59** [openshift/openshift-docs#29564]
### Which section(s) is the issue in?
RH Cluster Manager - Datacenter - Power page - the download RHCOS ISO button with URL below does not find a file
https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/latest/latest/rhcos-installer.ppc64le.iso

### What needs fixing?
URL https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/latest/latest/rhcos-installer.ppc64le.iso has no file found

**Comment by bobfuru** [comment]
Hi @jdbenson59 - thanks for reporting this issue. Could you please provide some more detail on where you are seeing this issue? I'm not finding where the specific RHCOS ISO button is located. Do you see it in the documentation or in the OpenShift Cluster Manager web console somewhere?

**Comment by bobfuru** [comment]
Thank you again for reporting this issue, @jdbenson59. 

I have found the "Download RHCOS ISO" button in OpenShift Cluster Manager that you are referring to, as shown in the following screenshot:
![Screen Shot 2021-07-21 at 4 26 59 PM](https://user-images.githubusercontent.com/47002677/126555523-374e0acc-dcec-431c-9258-21495fd9bed6.png)

The reported link [1] no longer exists because the ISO file has been renamed to `rhcos-live.ppc64le.iso`. The "Download RHCOS ISO" button now resolves to the correct location [2].

[1] https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/latest/latest/rhcos-installer.ppc64le.iso
[2] https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/latest/latest/rhcos-live.ppc64le.iso

I am going to close this issue.
