### ISSUE TITLE
[enterprise-4.5] Issue in file applications/pruning-objects.adoc

### ISSUE THREAD

**Issue by rajmechi** [openshift/openshift-docs#30085]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.5/applications/pruning-objects.html

**documentation mentioned Images that still contain pruned layers after pruning will be broken because the pruned layers that have metadata in the cache will not be pushed. Therefore, you must redeploy the registry to clear the cache after pruning:**

but `oc rollout restart deployment/image-registry -n openshift-image-registry` not included on both **Manually pruning images** ( example cronjob yaml file ) and **Automatically pruning images**  ( checked the cronjob that created by operator ) CronJob. 

![image](https://user-images.githubusercontent.com/39564006/109869027-620c8d00-7c36-11eb-8c96-6154b3307c49.png)

any reason for not including in cronjob when recommended as **must redeploy**  ?

**Comment by rolfedh** [comment]
This issue relates to modules/pruning-images-manual.adoc

**Comment by ehvs** [comment]
I do see the command `oc rollout restart deployment/image-registry -n openshift-image-registry` in the second bullet point in **Manually pruning images** , maybe the reason is to be intentionally a second step in the manual process. 
Also, I do not see any reference about the importance of redeploying the registry or disabling cache in the **Automatically pruning images** section. 

That said, I wonder if the command is needed when the process is done by the operator.
If yes, perhaps we could move the paragraph to below the title **Pruning images** ?
