### ISSUE TITLE
[enterprise-4.7] Issue in file virt/upgrading-virt.adoc

### ISSUE THREAD

**Issue by peterclauterbach** [openshift/openshift-docs#30524]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.7/virt/upgrading-virt.html#how-openshift-virtualization-upgrades-work

### What needs fixing?
This section talks about upgrading OpenShift Virtualization, but doesn't say anything about what happens to a VM when the OpenShift cluster itself is upgraded to a later version.  The OCP upgrade section doesn't talk about nodes in maintenance, or anything like that.
We need to clarify what happens to VM workloads when the OCP cluster is upgraded.  If this is documented elsewhere, please link in this issue.

**Comment by rolfedh** [comment]
Thanks for reporting this issue, @peterclauterbach. I'll make sure it gets to the writers that are working on the OCP > RHV docs.

**Comment by ousleyp** [comment]
Hi @peterclauterbach, thanks for bringing this to our attention. I think that we should put this information in the core docs (perhaps in addition to the virt docs) so that customers are more likely to see it before upgrading their clusters. I'm discussing this with @codyhoag who works on the core OpenShift upgrade documentation.

Who is the best SME to ask about what happens to VM workloads when the OCP cluster is upgraded? 
cc @fabiand @tiraboschi
