### ISSUE TITLE
[enterprise-4.7] issues from 4.7 docs: what's the reference link for Advanced RHCOS installation reference 

### ISSUE THREAD

**Issue by zzguang520** [openshift/openshift-docs#32515]
### Which section(s) is the issue in?
Hi all,
   I have tried to install openshift 4.7 (https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-bare-metal-network-customizations.html) in virtualbox, when I followed the steps in the documentation, I found that the VM's network was unavailable, I read the documentation carefully and found references links not marked  in the section of "
Creating Red Hat Enterprise Linux CoreOS (RHCOS) machines using an ISO image",  see the fifth operation for details：
5. Review the _Advanced RHCOS installation reference_ section for different ways of configuring features, such as networking and disk partitions, before running the coreos-installer.

I can see the "Advanced RHCOS installation reference" has been italicized, but can't found the reference link, would you share me the link or guide me how to config the networking? thank you

### What needs fixing?
pls mark the reference link

**Comment by zzguang520** [comment]
I have seen on the Internet that the nmtui or nmcli command is used to configure the network, I have tried to configured the network, but still can't connect or access the outside network, I checked through command "nmcli device status" that there is no network card eth0 configured by me and only have the network card lo.

The issues is from the network configuration, but I don't know how to configure the network correctly  


refe link for --copy-network: https://dustymabecom.sfo2.digitaloceanspaces.com/2020-11-18_RHCOS-ISO-Network.mp4

**Comment by bobfuru** [comment]
Hi @zzguang520 - thank you for raising this issue. We are currently unable to link directly to the specific section you mention ("Advanced RHCOS installation reference") due to technical toolchain limitations. Additional functionality is in the works for future versions of our documentation.

In the meantime, you can find that information here for OpenShift 4.7: https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#installation-user-infra-machines-static-network_installing-bare-metal-network-customizations

Regarding your other comment, there is more information in the "Using advanced networking options for PXE and ISO installations" documentation here:
https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#installation-user-infra-machines-advanced_network_installing-bare-metal-network-customizations
^This procedure addresses how to configure an ISO installation, including using the `--copy-network` option to copy networking configuration settings you configure using `nmcli` or `nmtui`. Docs for those commands should be available in the RHEL networking guide, for example: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/sec-configuring_ip_networking_with_nmcli

I hope that helps! Thanks again.

Closing issue.
