### ISSUE TITLE
[enterprise-4.7] Issue in file cli_reference/openshift_cli/getting-started-cli.adoc

### ISSUE THREAD

**Issue by husky-parul** [openshift/openshift-docs#32555]
### Which section(s) is the issue in?

Installing the OpenShift CLI on Linux

https://docs.openshift.com/container-platform/4.7/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli-on-linux_cli-developer-commands

### What needs fixing?
Under `Procedure` the link to download binary is incorrect. It points to `crc` installer.

**Comment by bergerhoffer** [comment]
@soltysh Do you have any ideas on the easiest way for someone to download the CLI? I know you can do it from the web console, but I believe we want something more generic here in the docs without having to have a cluster running.

The docs here point to https://cloud.redhat.com/openshift/install which looks like it's getting redirected now, and the interface there has changed since we wrote the docs. Users have to go through several steps (scrolling down, and then picking a provider and install type) before they get to a page where they can download it. Since neither of those things matter for the CLI (I think only OS does), it seems like unnecessary hoops to jump through. 

Seems like there should be a simpler way. Do you know of any, or have any thoughts on how we could improve this (or who to contact)?

**Comment by soltysh** [comment]
Officially, what the docs says is correct, we should probably update the docs to match the flow, which is:

cloud.redhat.com -> OpenShift -> Create Cluster -> (Pick one option) -> Download command-line tools  
or 
access.redhat.com -> Downloads -> Red Hat OpenShift Container Platform 

Semi-officially I'll be helping to refresh versions available on homebrew and chocolatey :smile:

**Comment by bergerhoffer** [comment]
Thanks @soltysh! Unless there's a reason not to, I think I'll update to use the customer portal method because I can link directly to the OCP downloads page. Seems much more straightforward than the first!

**Comment by bergerhoffer** [comment]
Closing, PR was merged. Updates will be live shortly
