### ISSUE TITLE
Search results in Dedicated docs result in 404 errors

### ISSUE THREAD

**Issue by sspeiche** [openshift/openshift-docs#3306]
It appears the search results return "3.2" links, which are no longer valid.

I went to https://docs.openshift.com/dedicated/welcome/index.html
and then searched for "Recreate" and got these results:

![image](https://cloud.githubusercontent.com/assets/727196/20795356/c0c10a26-b79e-11e6-89a6-bc533cabb151.png)

Clicking on this link gave me a 404

https://docs.openshift.com/dedicated/3.2/dev_guide/deployments.html

/fyi @spurtell

**Comment by bfallonf** [comment]
Hi @sspeiche 

Strangely enough, this came up a few days ago, and was fixed using redirects overnight. The links and process you give above work fine for me now.

I'll close this issue. Please let me know if there's something I'm missing and the 404s are still around.

**Comment by sspeiche** [comment]
I guess we need to redirect "latest" to "3.3", since that is what is latest. Seeing the "3.2" links and doc title is confusing.

![image](https://cloud.githubusercontent.com/assets/727196/20818880/ae70cf90-b7fe-11e6-83fa-f2740d9d6c7e.png)

**Comment by spurtell** [comment]
There is no version number anymore - it should just be https://docs.openshift.com/dedicated/

**Comment by bfallonf** [comment]
@sspeiche I'm not too sure what you mean. From what I understand, for OCP, it searches for the docs in the current branch you're in (latest, 3.2, etc). Not only that, there's tabs at the top of the search bar so that you can see the results in different branches.

@spurtell The dedicated docs only search the latest (so "dedicated" branch) either way.

As I said above, the results might be different from when this initially was reported to now. If you're talking about the URL beneath the results, it might just come down to "the redirects make it work". 

Maybe @nhr can shed some light on this.

**Comment by nhr** [comment]
Our docs.openshift.com and .org sites are indexed based on an XML file that we generate. You can actually view it in a browser at https://docs.openshift.com/sitemap.xml

This sitemap contains records for every file published on the site. I have confirmed that the file records for OpenShift Dedicated do not contain version numbers anymore.

I have manually triggered a re-indexing of this file through Google Custom Search. Note, however, that the index was last updated 2 days ago, which is long after the restructuring was done.
