### ISSUE TITLE
"microservices"

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#335]
In reference to: https://github.com/openshift/openshift-docs/blame/master/architecture/overview.adoc#L17

If Openshift is a monolithically compiled "fork" of Kubernetes where everything runs in a "single" OpenShift process, how is it a "set of microservices"?

Running OpenShift "on top of" Kubernetes has the implication of:

1) start kuberenetes
2) start OpenShift on the same server

Running OpenShift "alongside" Kubernetes has the implication of:

1) Start OpenShift pointed at an existing Kubernetes cluster

I know there are plans for the second scenario in the long-run, but I don't really understand the "set of microservices" part at all.

**Comment by adellape** [comment]
@thoraxe Given the [latest version](https://docs.openshift.com/enterprise/3.0/architecture/overview.html#what-is-the-openshift-architecture) of this topic, do you feel the issue is that we don't define what is meant by microservices there, or that you still question calling OpenShift a "set of microservices" at all?

cc @smarterclayton (original author of that bit)

**Comment by smarterclayton** [comment]
Everything inside OS is a decoupled units that work together.  Monolithic binary doesn't mean monolithic structure.  I don't care too much about the wording though.

**Comment by thoraxe** [comment]
I think that the current Red Hat understanding of the term "microservices" means distinct processes running. So, in my opinion, saying "OpenShift is a set of microservices that can run on top of (or alongside) a Kubernetes cluster" is very confusing because `ps -ef | grep shift | grep master` will only return one process.

**Comment by adellape** [comment]
How bout:

"OpenShift has a microservices-based architecture of smaller, decoupled units that work together. It can run on top of (or alongside) a Kubernetes cluster, with data about the objects stored in etcd, a reliable clustered key-value store."

**Comment by smarterclayton** [comment]
I don't think that matches much of the micro service JVM infrastructure we
have in middleware - service is really orthogonal to process.  Netflix
stack doesn't make that distinction either.  The boundary for micro
services is typically awareness or reference, and sometimes process or host.



On Jul 30, 2015, at 5:11 PM, Erik M Jacobs <notifications@github.com> wrote:

I think that the current Red Hat understanding of the term "microservices"
means distinct processes running. So, in my opinion, saying "OpenShift is a
set of microservices that can run on top of (or alongside) a Kubernetes
cluster" is very confusing because ps -ef | grep shift | grep master will
only return one process.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/openshift-docs/issues/335#issuecomment-126488724>
.

**Comment by thoraxe** [comment]
OK. I don't really have a dog in this fight. I just know that when I see "microservice" I think discrete, so it confused me.
