### ISSUE TITLE
Documentation on Supported Images Has Bad SEO

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/openshift-docs#3434]
When answering a question regarding Redis upstream with @bparees I had attempted to search for "OpenShift 3 Redis" and found nothing whatsoever for v3. The docs do have some [section](https://docs.openshift.org/latest/dev_guide/configmaps.html#configmaps-example-configuring-redis) using Redis as an example, but are we documenting the available imagestreams directly? If we are, the SEO for that page seems to be suboptimal. However we mean to help users answer "Can I run ____ on OpenShift v3" we should try to make it easy to get to that page from a Google search.

**Comment by bparees** [comment]
Redis just got released (technically it's not even released yet, it'll be part of the 3.5 release, since that's when it'll show up in the shipped imagestreams).  But yes we should get doc added... the SCL team would be the team to contribute that doc, @openshift/team-documentation you can work with @hhorak.

also @luciddreamz maintains the "supported technologies" page which i would expect to list this once 3.5 ships (or when online supports it).

**Comment by bfallonf** [comment]
Thanks, guys.

@aheslin @vikram-redhat this might be something to consider putting into upcoming sprint work. It might depend on what we can document in regards to Red Hat supportability rather than "can I run X". If Redis is being used as an example somewhere, but it's not supported in OCP untl 3.5, would that have to changed as well?

**Comment by vikram-redhat** [comment]
@bfallonf - thanks. Will discuss with @aheslin

**Comment by jawnsy** [comment]
Copy/pasting some thoughts from Jake (which were copy/pasted from a previous note) regarding SEO of the docs... I've done some light editing to get the formatting to look decent, hopefully I didn't mangle the meaning too much.  Read the following in Jake's voice:

>I've answered this in a few threads now, so I'm adding Harrison and copying and pasting my previous response. Note: At the time, 3.1 was the latest version, and I'm being lazy and not updating the response right now :)
>
>\---
>If we don't want the old docs to show up at all in search results, we could simply make the URLs for the latest version of our docs 'latest' and block the other versions of our docs from showing up with a robots.txt file. This might cause some issues if people are copying and pasting links from their address bar intending to send users to a specific version of our docs.
>
>If the page paths are relatively stable, we could try something like this:
>
>1) For all pages that are part of the **latest** revision of the docs, we can set a hidden/metadata element on the page referencing the 'latest' URL:
>
>>    <link rel="canonical" href="https://docs.openshift.com/enterprise/latest/dev_guide/app_tutorials/ruby_on_rails.html">
>
> _Note: The actual URL would remain ...enterprise/3.1/dev_guide/..._
>
> 2) We can update the redirect from latest so that it checks for the existence of an actual file before redirecting. If the file isn't found, we can fall through to redirecting to an older version of the docs: 
>
>> location ~* ^/enterprise/latest/(?<page_path>.*)$ { 
>>      if(-f ~* "^/enterprise/3.1/$page_path") {
>>        rewrite ^/enterprise/latest/(.*)$ /enterprise/3.1/$1 permanent;
>>      }
>>     
>>      if(-f ~* "^/enterprise/3.0/$page_path") {
>>        rewrite ^/enterprise/latest/(.*)$ /enterprise/3.0/$1 permanent;
>>      } 
>>    }
>
> The rel="canonical" link would tell Google to index the enterprise/latest URL, which would bring people in to the site to the current latest version of the docs. Older versions of the docs would have the rel="canonical" link set to their actual page URL, such as enterprise/3.0, allowing them to still be reachable. Effectively, this would make the latest version of our docs show up in search results immediately, while the older version of the docs would be indexed and show up "eventually" in the search results. If the page paths changed in the new docs, the NGINX redirect above would allow the URL to fall through to an older version of the docs to prevent 404s from old/external links.

**Comment by jawnsy** [comment]
I realize the above isn't completely relevant to the current issue (I reflexively dug it up and added it here because it mentioned "SEO") but it seems it'd help with this as well. Searches currently turn up arbitrary versions of the docs, so ensuring that the latest version gets indexed correctly would make sure users always see the latest & greatest.

**Comment by aheslin** [comment]
So I think there are 2 issues here. Correct me if I'm wrong. 
1) Redis is showing up in the docs already and it's not supported by OCP yet. Right? I did see it so if it's not supported yet, we need to take it out because it could cause problems for support.
2) Searching pulls up arbitrary versions of the docs and we want to pull up the latest docs. I think I know someone on the portal team I could ask about that, but I don't know if it would help docs.openshift.com. I'm open to working on that though.

**Comment by luciddreamz** [comment]
Redis should be in the Origin docs, but Redis (3.2), PHP 7, MySQL 5.7, and Perl 5.24 will not be hitting OCP until 3.5 from what I've heard. We will be releasing all of those to OpenShift Online any day now, so they can show up in Origin/Online docs.

**Comment by stevekuznetsov** [comment]
@aheslin 

> Redis is showing up in the docs already and it's not supported by OCP yet. Right?

This is not the best but I *was* looking for Origin latest docs specifically, and I just wasn't seeing any documentation for supported images.

> Searching pulls up arbitrary versions of the docs and we want to pull up the latest docs. 

My personal opinion is if we are going to make the latest docs show up when someone is Googling, it needs to be crystal clear (I'm thinking huge red banner) that these documents are not for whatever OSE release that person is using. A really frustrating part of Ansible right now, for example, is they only publish one version of documentation, for latest development version, and it's super hard to know if what you're reading about is actually supported in the product you have installed.
