### ISSUE TITLE
[enterprise-4.7] Issue in file virt/about-virt.adoc

### ISSUE THREAD

**Issue by methadata** [openshift/openshift-docs#34456]
### Which section(s) is the issue in?

What you can do with OpenShift Virtualization

### What needs fixing?

As OCS product name has been replaced by ODF, the following paragraph:

> "OpenShift Virtualization is tested with OpenShift Container Storage (OCS) and designed to use with OCS features for the best experience." 

should say instead:
> "OpenShift Virtualization is tested with OpenShift Data Foundation (ODF) and designed to use with ODF features for the best experience."

**Comment by stevsmit** [comment]
@methadata I have created a ticket for this issue but will not be able to close it until the release of OCS 4.9, when the name change from OCS to ODF goes live in the docs. Thanks for filing this ticket. 

I will merge the PR ~December.

**Comment by apinnick** [comment]
> @methadata I have created a ticket for this issue but will not be able to close it until the release of OCS 4.9, when the name change from OCS to ODF goes live in the docs. Thanks for filing this ticket.
> 
> I will merge the PR ~December.

@stevsmit @ctomasko 

Steve, your PR was never merged. It was closed, so I reopened it. The name still needs to be fixed.

**Comment by ctomasko** [comment]
@stevsmit  @apinnick As the OpenShift Virtualization (CNV) DPM, I prefer that a CNV writer investigate and resolve issues in the virtualization area. Please coordinate with @ousleyp to ensure CNV quality standards. Thank you

**Comment by stevsmit** [comment]
Thanks @ctomasko. There is a thread that involved Ken Hartsoe, Ananja Sriram, and Vikram where we discussed that the ODF team was going to handle these changes. From Ken back in September: 

In order to better understand this effort, is there a way to determine which OCP files contain "OpenShift Container Storage"? Note that our team is only rebranding the OCS 4.9 documentation: earlier OCS documentation versions will remain as OCS, so any updates to OCP would be within the OCP 4.9 documentation set.

I'm closing my associated PR.

**Comment by ousleyp** [comment]
@ctomasko The PR LGTM, but because this change hasn't been made anywhere else in the 4.9 branch yet, I think we should keep it closed. It would probably make more sense for someone to change all of the instances simultaneously.
