### ISSUE TITLE
Missing wildfly s2i documentation

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-docs#3453]
The centos7 imagestreams (https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json) include Wildfly which perhaps should be documented

The java documentation also points to an archived fabric8io repo https://github.com/fabric8io-attic/java-main/tree/master 

If they're documented, should the java s2i images be included as part of the centos7 imagestreams?

**Comment by jawnsy** [comment]
Hmm. It might be a good idea to use a separate image stream for community images (s2i-wildfly used to be in `openshift` but was moved to `openshift-s2i` some time ago).

@bparees can you chime in on this one?

**Comment by bparees** [comment]
wildfly isn't going to get officially documented because it's not a supported image.

the Java doc is indeed pointing to a fairly pointless image, we're working on a new java s2i image and the doc will be updated to reflect that once it's ready/available.

and I think we want to retain wildfly in the centos imagestream list because it's a fairly fundamental image for people who aren't using the jboss images.

**Comment by andrewklau** [comment]
The documented java image does seem to point through to https://github.com/fabric8io-images/s2i which is getting updated

**Comment by vikram-redhat** [comment]
Closing this based on Ben's response.
