### ISSUE TITLE
[enterprise-4.7] Issue in file backup_and_restore/graceful-cluster-shutdown.adoc

### ISSUE THREAD

**Issue by gpulido-redhat** [openshift/openshift-docs#34588]
### Which section(s) is the issue in?

Shutting down the cluster

### What needs fixing?

In the document, the command to shutdown all the nodes is given as follows:

```
$ nodes=$(oc get nodes -o jsonpath='{.items[*].metadata.name}')
$ for node in ${nodes[@]}
do
    echo "==== Shut down $node ===="
    ssh core@$node sudo shutdown -h 1
done
```

However this does not work on any infrastructure because the nodes' hostnames are not always registered on the DNS. I think it would be better to use the IP addresses of the nodes to connect to them.

**Comment by jboxman** [comment]
cc @bergerhoffer

**Comment by bergerhoffer** [comment]
@sttts Can you weigh in on this? In some of the DR docs, we do "oc debug node/<node_name>" instead of SSHing. Example here [1]. wdyt?

@gpulido-redhat would oc debug work better for your cases?

[1] https://docs.openshift.com/container-platform/4.8/backup_and_restore/replacing-unhealthy-etcd-member.html#restore-replace-crashlooping-etcd-member_replacing-unhealthy-etcd-member

**Comment by gpulido-redhat** [comment]
> @sttts Can you weigh in on this? In some of the DR docs, we do "oc debug node/<node_name>" instead of SSHing. Example here [1]. wdyt?
> 
> @gpulido-redhat would oc debug work better for your cases?
> 
> [1] https://docs.openshift.com/container-platform/4.8/backup_and_restore/replacing-unhealthy-etcd-member.html#restore-replace-crashlooping-etcd-member_replacing-unhealthy-etcd-member

Hi @bergerhoffer , for me the important part is that the instructions given to shutdown the cluster nodes work reliably on any infrastructure that is correctly deployed. If you consider oc debug is the best option for that, I'm cool with it.
