### ISSUE TITLE
[enterprise-4.8] Issue in file installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc

### ISSUE THREAD

**Issue by mistergareth** [openshift/openshift-docs#35863]
### Which section(s) is the issue in?
Step 11 which creates the virtual bridge interface names and links them to the $PUB_CONN and $PROV_CONN NICs.

### What needs fixing?
We've hit this issue several times with a Partner when we are trying to deploy into their environment via VPN, which should work. However, the IPs of the two NICs ($PUB_CONN and $PROV_CONN) need to reserved IPs in the DHCP server. So that when Step 11 completes the "nmcli" commands, they come back and we can ssh in again.

I'm sure this is already documented in a different, previous section (prerequisites or Networking), but it would be good to add a call-out or warning here to be sure the two IPs are reserved in the DHCP server, or the interfaces will come up with new different IPs that you expect. Maybe with a link to the prerequisites section that describes it.

It would just be a plus to have an in-place reminder before running Step 11 that without reserved IPs you won't be able to get back in.

**Comment by johnwilkins** [comment]
@mistergareth noted. I've made an update locally. It strikes me that you would only need to do this on the `PUB_CONN` nic in order to log in again since the provisioning network is only for provisioning. We do have a note to reserve an IP address on the DHCP server, but I believe those are specifically reserved on the baremetal network. Can you verify?

**Comment by johnwilkins** [comment]
@mistergareth how about this? 

[IMPORTANT]
====
You must reserve the IP address of the `PUB_CONN` NIC in the DHCP server before proceeding with this step. See "Dynamic Host Configuration Protocol (DHCP) requirements" in the "Network Requirements" section of the "Prerequisites" for details on reserving an IP address so that it becomes a static IP address. Failure to reserve the IP address may result in the NIC using a different IP address after bringing the network up, thereby impeding your ability to reconnect to the provisioner node.
====
