### ISSUE TITLE
[enterprise-4.8] Issue in file post_installation_configuration/storage-configuration.adoc

### ISSUE THREAD

**Issue by peterclauterbach** [openshift/openshift-docs#38499]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.8/post_installation_configuration/storage-configuration.html#post-install-deploy-OCS
Deploy Red Hat OpenShift Container Storage

### What needs fixing?
There are stale links in the OCP docs point to older OCS docs.
Some of the links in here point to OCS 4.7, and some even point to older OCS 4.5.
I'd expect that if that same section exists in the latest version of OCS 4.8, the link would point to that.
I know the corresponding OCS release is a few weeks behind the OCP release.
I suspect this mismatch of older OCS links is across several OCP versions of this table.

**Comment by jboxman-rh** [comment]
@peterclauterbach do we know what the correct links are for this?

**Comment by peterclauterbach** [comment]
I do not, but one of the OCS doc team or product managers should be able to help.

**Comment by jboxman-rh** [comment]
@dmoessne, do you know what links should go here now? Thanks!

**Comment by dmoessne** [comment]
@jboxman-rh  

Well, I am neither docs nor PM team, but surely I can share my view:

Generally speaking  OCS n supports OCP n and n+1 (*no longer* n-1), so for example OCS 4.7 supports OCP 4.7 and 4.8 no longer 4.6 (as per https://issues.redhat.com/browse/KNIP-1678)
So in my mind we should refer always to the same version in the OCS docs as OCP is (keeping in mind what Peter said that OCS is normally joining a bit later)

Also, I want to question if it makes sense to refer to all the guides detailed as we do it  with the table instead of rather pointing to the high level doc overview, like https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.8
especially as the amount of guides for different setups is grown on OCS side

**Comment by bobfuru** [comment]
There is a proposed fix to remove the table in the OCP docs that is being tracked by the ODF/OCS docs team: https://issues.redhat.com/browse/OCSDOCS-515.

**Comment by peterclauterbach** [comment]
I understand maintaining this table can be painful to align all the semi-synchronous releases, or even that this table should be the first place that and admin would land in the ODF documentation, not OpenShift.
The reality I often hear from customers is that navigating our docs is a treasure hunt. The individual content is good, but scattered. I need to go to 3 different places to figure out this one workflow.
Regardless of how we fix this, are there any analytics that indicates some number of customers visit the links in this table?

**Comment by vikram-redhat** [comment]
> Regardless of how we fix this, are there any analytics that indicates some number of customers visit the links in this table?

We don't track link clicks external to docs.openshift.com. These links to OCS docs goes to customer portal and someone from that docs team could give that data (as to how many links came from docs.openshift.com). 

Since that page was launched (4.8 GA in late July), it has been viewed 1,162 times if that gives an indication.

> The individual content is good, but scattered. I need to go to 3 different places to figure out this one workflow.

This might be a good question to raise with the OCS/ODF BU team if they want to or should publish with docs.openshift.com.
