### ISSUE TITLE
Document that the pathType of the Ingress object is required

### ISSUE THREAD

**Issue by ugiordan** [openshift/openshift-docs#38551]
If a user create a route through an Ingress object by copying the example provided at [Creating a route through an Ingress object](https://docs.openshift.com/container-platform/4.7/networking/routes/route-configuration.html#nw-ingress-creating-a-route-via-an-ingress_route-configuration), the following error is thrown:

**Error "Required value: pathType must be specified" for field "spec.rules[0].http.paths[0].pathType"**

It must be specified that the `pathType` option is required as described in the [Kubernetes doc](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types):

"Each path in an Ingress is required to have a corresponding path type. Paths that do not include an explicit pathType will fail validation."

https://bugzilla.redhat.com/show_bug.cgi?id=2014018

For 4.7+

**Comment by absynth76** [comment]
I'll add on top of this one, it's not only mandatory, it's also limited since openshift 4.8, we ran in a situation that the route was not created at all, indeed, on the controller manager code there was an update:
https://github.com/openshift/openshift-controller-manager/blob/release-4.8/pkg/route/ingress/ingress.go#L433

The "pathType: Exact" is no more supported.
