### ISSUE TITLE
Post Hook for the Pod before it is terminated

### ISSUE THREAD

**Issue by bortek** [openshift/openshift-docs#3889]
Hi

I am looking for a way to execute a command before the pod is terminated/shutdown . K8s has PostStart and PreStop hooks (https://kubernetes.io/docs/user-guide/container-environment/#container-hooks ) which are working probably doing what I want. But I need a corresponding mechanism in the Openshift?

So far I found only deployment Hooks for the pods but they are executed before deploy and before image deploy (https://docs.openshift.com/enterprise/3.1/dev_guide/deployments.html#pod-based-lifecycle-hook). 

Anyone knows how can I achieve what I want ?

Best
/B

**Comment by php-coder** [comment]
This is a repository for OpenShift documentation and that's why you still didn't get any feedback. I'd suggest you to rather ask on:
- mailing list (http://lists.openshift.redhat.com/openshiftmm/listinfo/users)
- StackOverflow (http://stackoverflow.com/questions/tagged/openshift-origin)
- (as a last resort) OpenShift issue tracker (https://github.com/openshift/origin/issues)
