### ISSUE TITLE
[RHACS] Issue in file configuration/configure-proxy.adoc

### ISSUE THREAD

**Issue by gaurav-nelson** [openshift/openshift-docs#39288]
### Which section(s) is the issue in?
https://docs.openshift.com/acs/3.66/configuration/configure-proxy.html#configure-proxy-during-installation_configure-proxy

### What needs fixing?
There's a wrong filename and a misleading comment on Helm (in my opinion). The user should not modify Helm templates directly but instead configure the Helm chart by providing the respective configuration values.

### Fix
1.  Open the configuration file `central/00-proxy-config-secret.yaml` from your
deployment bundle directory.
2. If you are using the Helm chart, follow the documentation contained in the file`values-private.yaml.example` to configure proxy related settings.

**Comment by gaurav-nelson** [comment]
@mtesseract I've created the issue here where the docs are. 

Q. Does that mean we need to remove the YMAL configuration file example and instead add how to configure proxy in `values-private.yaml` file?

**Comment by mtesseract** [comment]
Hi. There are two different workflows being supported currently:

1. The "classical" deployment bundle workflow: In this case the user edits the YAML template for the proxy settings contained in the bundle directory and then proceeds with the bundle installation process.

2. The more modern Helm based workflow: In this case user is not expected to edit the YAML template for the specific Kubernetes resource directly, instead the user configures the proxy settings via an exposed configuration interface, namely by setting `env.proxyConfig`. This can happen by crafting a custom `values-private.yaml` based on `values-private.yaml.example` and adjusting the `proxyConfig` settings there.

Nothing related to these workflows has changed.

Only, for the first workflow the filename was wrong. And the remark for the second workflow is also wrong.

To answer your question: The YAML from the documentation should not be removed, as workflow 1 is still supported.
We could definitely elaborate on the Helm workflow, since that is currently only very briefly mentioned in the remark and it is nowadays, I would say, the recommended workflow. Since the `values-private.yaml.example` is in my opinion pretty self-explanatory I did not see the immediate need to flesh this out. But, in order to underline that the Helm based workflow is actually recommended it could be a good idea to let the documentation reflect this by describing it more thoroughly.
