### ISSUE TITLE
[dedicated] Issue in file support/getting-support.adoc

### ISSUE THREAD

**Issue by InfoSec812** [openshift/openshift-docs#40302]
### Which section(s) is the issue in?
Submitting A Support Case: https://docs.openshift.com/dedicated/support/getting-support.html#support-submitting-a-case_getting-support

### What needs fixing?
The current docs say that you need to be `cluster-admin`, and that it not possible in OSD...

**Comment by bergerhoffer** [comment]
CC @EricPonvelle @pneedle-rh

**Comment by InfoSec812** [comment]
/remove-lifecycle stale

This issue is still present and needs to be resolved.

**Comment by xueli181114** [comment]
I reviewed the doc and some places need to be updated.
1. Submitting a support case ->  Prerequisites ->You have access to the cluster as a user with the cluster-admin role. -- This line should be used for customers getting cluster ID with command `$ oc get clusterversion -o jsonpath='{.items[].spec.clusterID}{"\n"}'` . Customers can create cluster-admin user to an OSD cluster once there is related capability set to the cluster. But I am thinking, there had been two ways for customers to get the cluster ID, can we just remove this one?
2. Submitting a support case -> Procedure -> step 7 -> Navigate to Home → Dashboards → Overview. -- Where is Dashboards? I think maybe this means cluster details page?

**Comment by xueli181114** [comment]
Sorry,  just double confirmed with the cluster-admin feature owner. The CCS OSD cluster can create cluster-admin user without capability. Only standard OSD cluster which is using RH account should have the capability.

**Comment by EricPonvelle** [comment]
@InfoSec812, thanks for bringing this up. I simply removed the line about needing to be a `cluster-admin` of any sort since these instructions are for submitting a ticket, which do not require elevated permissions/roles. You can see the updated documentation is live now.

1. [OSD Support](https://docs.openshift.com/dedicated/osd_architecture/osd-support.html#support-submitting-a-case_osd-getting-support)
2. [OCP support](https://docs.openshift.com/container-platform/4.11/support/getting-support.html#support-submitting-a-case_getting-support)
3. [Serverless Support](https://docs.openshift.com/container-platform/4.11/serverless/serverless-support.html#support-submitting-a-case_serverless-support)
4. [Service Mesh support](https://docs.openshift.com/container-platform/4.11/service_mesh/v2x/ossm-troubleshooting-istio.html#support-submitting-a-case_troubleshooting-ossm)

**Comment by InfoSec812** [comment]
Thank you so much!
