### ISSUE TITLE
[enterprise-4.9] Issue in file nodes/nodes/nodes-nodes-rebooting.adoc

### ISSUE THREAD

**Issue by borball** [openshift/openshift-docs#41216]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.9/nodes/nodes/nodes-nodes-rebooting.html#nodes-nodes-rebooting-gracefully_nodes-nodes-rebooting

### What needs fixing?
1.  --force has to be used due to error like 'error: cannot delete Pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet (use --force to override): openshift-marketplace/certified-operators-nk64h, openshift-marketplace/community-operators-5ssnm, openshift-marketplace/redhat-marketplace-262nf, openshift-marketplace/redhat-operators-t9pk7'

oc adm drain <node1> --ignore-daemonsets --delete-emptydir-data --force

2. For a SNO (Singlle Node OpenShift) cluster which has PodDisruptionBudget defined, the PodDisruptionBudget has to be manuallly deleted or the deployment shall be manually scaled down to the number less than the min available defined in the PodDisruptionBudget, otherwise the draining won't be happeneing due to error 'error when evicting pods/"nginx-67c559b4f6-9f6vb" -n "default" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.'

oc delete pdb <pdb> -n <namesapce>
or:
oc scale deployment <deployment> -n <namespace> --replicas=0

Once the node is rebooted, deployment can be scaled back to the desired one, or enable the PodDisruptionBudgets back.

**Comment by mburke5678** [comment]
@borball Thanks for this issue and your PR. 

What is your specific concern? On the systems I have looked at while researching this issue, I see that there are multiple PDBs installed by default on a cluster. Far too many to suggests people delete them (and I am not sure how they could re-create the default PDBs). 
I do see that if I try to drain the node where these PDBs are located, I get errors and the drain doesn't complete. I can use the `--disable-eviction=false` flag with the `oc adm drain` command. This drains all the pods possible from the node (not all pods, by design). Then you can do the reboot (I assume).
Am I incorrect here?

**Comment by borball** [comment]
@mburke5678 , thanks for following up on the issue and PR. 
The major concern for this issue is the reboot procedure on the SNO(single node openshift) cluster. I have sent a PR(https://github.com/openshift/openshift-docs/pull/43659) to fix the issues mentioned above, not sure why it is not linked here, can you please review the PR?

**Comment by borball** [comment]
@mburke5678 When I did the test on 4.9 I didn't see the default PDBs on the cluster, those default PDBs on the 4.10 cluster are probably managed by the operator itself, that is why your change came back to the previous state automatically. 

About the custom PDBs, one thing we forgot in the current doc is that on the SNO cluster if we don't remove the custom PDBs or manually scale the deployment replica to 0, it was not possible to drain(include cordon) or cordon the node, you will see some PDBs related warnings when you run 'oc adm drain' or 'oc adm cordon'.  Part of the PR is going to fix this issue.

The other part of the PR is to fix the situation mentioned in comment https://github.com/openshift/openshift-docs/issues/41216#issuecomment-1136642218.  And this one is more concerned by one of the customers who use 'oc login' to manage the cluster rather than kubeconfig file.

**Comment by mburke5678** [comment]
@borball Thank you for your patience and persistence. I want to make sure I understand the problem and the solution.

I added your additional steps and information as notes, because it seems (to me) to be an edge case. Please take a look at [this internal-only preview](http://file.rdu.redhat.com/~mburke/update-node-reboot-procedure/nodes/nodes/nodes-nodes-rebooting.html#nodes-nodes-rebooting-gracefully_nodes-nodes-rebooting) and let me know if this addresses your concerns and I can move this along.

**Comment by borball** [comment]
@mburke5678 Thank you for the preview page, my first look is good, I may verify the new procedure carefully in the coming week to make sure we don't miss anything.

**Comment by djuran** [comment]
I don't think messing with PDBs of various applications is the right things to do. 
Added a comment to https://github.com/openshift/openshift-docs/pull/43659

**Comment by mburke5678** [comment]
[PR is merged](https://github.com/openshift/openshift-docs/pull/46090). Closing.
