### ISSUE TITLE
[enterprise-4.9] Issue in file sandboxed_containers/deploying-sandboxed-container-workloads.adoc

### ISSUE THREAD

**Issue by omertuc** [openshift/openshift-docs#41813]
### Which section(s) is the issue in?
Installing the OpenShift sandboxed containers Operator using the CLI

### What needs fixing?
The "Prerequisites" say that:

> You have subscribed to the OpenShift sandboxed containers catalog.

But then the "Procedure" goes on to explain how to do just that, so this is not really a prerequisite. At-least if my understanding is correct.

**Comment by sagidlow** [comment]
@MirzWeiss assigning this to you since you are now the sandboxed containers writer.

**Comment by stevsmit** [comment]
Documentation for Sandboxed Containers no longer exists in the OpenShift Container Platform repository. Docs have been moved to their own repo. Because of this, I am closing the issue (as it exists outside of OCP docs repository). 

https://docs.openshift.com/container-platform/4.13/sandboxed_containers/sandboxed-containers-moved.html

@MirzWeiss I'm not sure if this is still an issue, but it was requested that I tag you, and let you know why I am closing it.

Thanks!
