### ISSUE TITLE
Docker Volumes in Openshift Online

### ISSUE THREAD

**Issue by thrasher-redhat** [openshift/openshift-docs#4229]
https://github.com/openshift/openshift-docs/blob/master/creating_images/guidelines.adoc
https://docs.openshift.com/online/creating_images/guidelines.html

In the "Use Volumes for Persistent Data" section, it states that "Images should use a Docker volume for persistent data."  However, Docker Volumes are disabled for Openshift Online.

Not sure how much needs to be changed here - hopefully someone with a little more subject matter expertise will know.

**Comment by ahardin-rh** [comment]
@thrasher-redhat Thanks!
 @Miciah @tiwillia Thoughts? May just be that we need to add some ifdef/endif statements to differentiate what is relevant for Online and the other product flavors.

**Comment by tiwillia** [comment]
I think "Images should use a volume for persistent data" is an acceptable change. By `docker volume`, I think they are referring to a volume mounted in the docker image.

**Comment by Miciah** [comment]
I'm not sure what "Docker volumes are disabled" means.

We're specifically talking about the `VOLUME` directive in `Dockerfile`, right? That directive in itself is fine, and it is used in images we provide for Online.

However, it might be worth providing a note on what actually happens when you use such an image:

* You can invoke `oc new-app` on an image with a `VOLUME` directive, and `oc new-app` will create a dc with an emptydir volume and volume mount, mounting the emptydir volume at the mount point specified with the `VOLUME` directive.  Note that an emptydir volume is **ephemeral**.

*  If you have deployed an image with `oc new-app`, you can use [`oc volume`](https://docs.openshift.com/online/dev_guide/volumes.html#updating-volumes) to replace an emptydir volume with a **persistent** volume.

* If you define a template, it can specify an **ephemeral** emptydir volume **or** a **persistent** volume claim (for which, in Online, we would automatically provision a persistent volume), and then you can use `oc new-app` to instantiate that template, and you get whatever volume is defined therein.  (In fact, in many cases, we have both an "-ephemeral" version and a "-persistent" version of a template.  It might be helpful if the [template guide](https://docs.openshift.com/online/dev_guide/templates.html) had an example with a persistent volume claim.)

Of course, you don't *need* to specify the `VOLUME` directive in order to be able to mount a volume into an image; you can always use `oc volume` or specify a volume mount in your dc or template using any arbitrary directory that exists in the image as the mount point.  For this reason, the `VOLUME` directive could be considered primarily advisory, a hint that a volume (whether emptydir or pv) is expected to be mounted there.

**Comment by Miciah** [comment]
Most likely, in that document, the phrase "Docker volume" (which links to Docker documentation) is just some really stale phrasing that doesn't apply to OpenShift or Kubernetes (we have a lot of that).

**Comment by Miciah** [comment]
I think "Docker volumes are disabled" is supposed to convey that if you create a pod with an image that was defined with a `VOLUME` directive, and you do *not* specify a volume in the podspec, then the pod will not start.  This is not a problem if you use `oc new-app` (which specifies an emptydir volume for you in the case of such an image), and it is not a problem if you *do* specify the volume in your podspec.

**Comment by vikaschoudhary16** [comment]
@Miciah  documentation should be updated with your above comment.
I recently investigated the following issue: 
https://github.com/openshift/origin/issues/16211

And the behavior is consistent with what you described above. post hook container fails if "-v" is not passed, but regular container created fine because template adds emptydir volume.

**Comment by rvansa** [comment]
In my case I hit a strange behaviour when creating the deploymentconfig manually (actually using fabric8 openshift-client). Using MariaDB 10.3 as the base image I found that `/var/lib/mysql` was mounted with `mysql:mysql` user/group when I did not specify the volume. `docker inspect` was reporting this directory as mounted, though, and I also could not chown/chgrp/chmod this directory from `Dockerfile`. Contrary to what you describe above, though, the pod started up correctly.

After adding volume (emptyDir) and volumeMount do deploymentconfig it got mounted as `root:100033000` which matches the groupid of the user - so it works as it should.
