### ISSUE TITLE
[enterprise-4.8] Issue in file migration_toolkit_for_containers/about-mtc.adoc

### ISSUE THREAD

**Issue by Tekwriter1221** [openshift/openshift-docs#42944]
### What needs fixing?    Migration Toolkit for Containers - should be all lower case per the Red Hat master product list.

**Comment by apinnick** [comment]
> ### Which section(s) is the issue in? Header
> ### What needs fixing? Migration Toolkit for Containers - should be all lower case per the Red Hat master product list.

Can you send me a link? I do not see MTC in the [master product list](https://docs.google.com/spreadsheets/u/2/d/1DLS_lS3VKidgZIvcLmLp9BoiqptkvqHWfe1D5FD2kfk/pubhtml?gid=1259317633&single=true). I think I opened a ticket a while ago to add it but it probably never got assigned.

The migration toolkits were rebranded about two years ago as "[Migration Toolkit for X](https://access.redhat.com/migration-toolkits)" or Migration Toolkit for X by Red Hat", since they are solutions, not products. I have never heard that branding has changed so that they are lower case. If you can send me a link showing me where you found the directive, I will deal with it. Thanks.

**Comment by Tekwriter1221** [comment]
Here is the link to the[ Master Product List,](https://docs.google.com/spreadsheets/d/1DLS_lS3VKidgZIvcLmLp9BoiqptkvqHWfe1D5FD2kfk/edit#gid=1375785039) Technologies tab, line 56. 
And, here is the link to the webpage in question: [
](https://docs.openshift.com/container-platform/4.8/migration_toolkit_for_containers/about-mtc.html)

To be clear, the issue is not with the initialism MTC, but rather the "migration toolkit for containers." I am part of the proposal team for public sector and several of the SAs are copy/pasting from Red Hat webpages that are either capitalizing the technology name, or adding "Red Hat" in front of it, or both.  Thanks for your help!

**Comment by apinnick** [comment]
I was wondering whether I was not seeing the tabs. They did not load when I checked earlier.

Look at the line about doc style guides. That is the usage we follow.
![image](https://user-images.githubusercontent.com/31725355/157287813-b104de22-3031-4428-a55e-75f621e037a5.png)
