### ISSUE TITLE
[enterprise-4.9] Issue in file nodes/containers/nodes-containers-sysctls.adoc

### ISSUE THREAD

**Issue by caorong** [openshift/openshift-docs#44908]
### Which section(s) is the issue in?

spelling error

Wait for the cluster to reboot `usng` the machineconfigpool object status fields

// should change to

Wait for the cluster to reboot `using` the machineconfigpool object status fields

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

Link: https://docs.openshift.com/container-platform/4.10/nodes/containers/nodes-containers-sysctls.html#nodes-containers-sysctls-unsafe_nodes-containers-using

This has been fixed in newer releases, so the problem is only on versions 4.6-4.10 now. Whoever takes this: the change should be made against the enterprise-4.10 branch. Ping me with any questions!

/remove-lifecycle rotten

**Comment by bergerhoffer** [comment]
@tonytheleg has submitted PR#51431 to resolve this issue. Thanks for your contribution!

**Comment by bergerhoffer** [comment]
Closing since the above PR has been merged!
