### ISSUE TITLE
Some questions about doc guidelines

### ISSUE THREAD

**Issue by thatdocslady** [openshift/openshift-docs#4500]
As part of our work on Minishift[1] docs we are striving to align with OpenShift doc guidelines[2]. During the discussions with our engineering team, a few questions came up that we hope to clarify here so that we can implement the most effective set of conventions:

1. What is the context/background for the requirement to use xref tags[3] in internal cross-references as opposed to different ways to tag links (for example double angle-brackets <<>>)?

2. The guidelines indicate to only use four dashes (----) before and after code blocks[4], which implies that no other tagging should be used. However, there are some places in the OS docs where source tags (i.e. [source,json]) are also added before code blocks for example here[5]. If this is an acceptable way to tag code blocks, are there specific guidelines that can/should be explicitly outlined, so that we don't risk using tags that might break the publication toolchain upstream/downstream?

3. Are there any restrictions/guidelines for writing one-sentence-per-line format (as in, no manual line breaks in the source adoc file)? Will this have impact/consequences on the publication toolchain? No guidelines exist for this at the moment.

Note that right now we are only publishing the docs upstream to docs.openshift.org[6], but most content is planned to be reused downstream.

[1] https://github.com/minishift/minishift
[2] https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc
[3] https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#internal-cross-references
[4] https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#formatting
[5] https://raw.githubusercontent.com/openshift/openshift-docs/master/admin_guide/managing_projects.adoc
[6] https://docs.openshift.org/latest/minishift/

**Comment by adellape** [comment]
> What is the context/background for the requirement to use xref tags[3] in internal cross-references as opposed to different ways to tag links (for example double angle-brackets <<>>)?
> 

Deferring to @vikram-redhat on this one because I can't remember the specifics, but I believe there was a Customer Portal-related build reason why we wanted `xref`. We used to use `link` for internal references too, but then migrated all internal links to `xref` and now use `link` for external links for this reason that I can't remember. Another pro-`xref` reason could be that it's easier to grep for than `<<`.  (FWIW, other RH teams also note the same preference for `xref` in their [contrib guidelines](https://gitlab.cee.redhat.com/red-hat-jboss-enterprise-application-platform-documentation/eap-documentation/blob/master/internal-resources/asciidoc-writing-guide.adoc#links_to_sections_within_the_same_guide), and I think those are feeding into the WIP CCS-wide AsciiDoc guidelines.)

Once we confirm what that Customer Portal reason was, we can update our guidelines to state the background more clearly.

> The guidelines indicate to only use four dashes (----) before and after code blocks[4], which implies that no other tagging should be used. However, there are some places in the OS docs where source tags (i.e. [source,json]) are also added before code blocks for example here[5]. If this is an acceptable way to tag code blocks, are there specific guidelines that can/should be explicitly outlined, so that we don't risk using tags that might break the publication toolchain upstream/downstream?
> 

Yes, these are fine for both AsciiBinder and Customer Portal builds, the guidelines just don't currently mention them either way. There were previously some weird rendering issues w/ some of the highlighting (YAML in particular IIRC), but I'm pretty sure they've been fixed on the Portal side now. I haven't noticed any problems in our Portal builds lately.

We can update our guidelines to say "go for it" WRT source highlighting.

> Are there any restrictions/guidelines for writing one-sentence-per-line format (as in, no manual line breaks in the source adoc file)? Will this have impact/consequences on the publication toolchain? No guidelines exist for this at the moment.

No restrictions/guidelines as far as publication to worry about. I thought we had a bit in there previously about wrapping at 80 columns (so that the source is easily readable everywhere / doesn't scroll) but looks like it never made it in. GitHub diffs definitely get less fun when the modified content has mixed usage. @vikram-redhat WDYT?

**Comment by vikram-redhat** [comment]
We used xrefs because it allowed us to construct/preserve those links in the different formats (single html, paged, PDF, etc...) that are used by the portal. If you use link:, you can only ever generate a paged html format, as if you generate anything else those links will no longer work. Also, the use of xref over <<>> was preferred because it was the general format for other tags (link:, image:, include:: etc.).

As for the 80 columns thing.. :) my thoughts are that it is an individual thing, and I have no qualms whatever everyone wants to use to make their life easier. That is my way of saying, I don't want to mandate one over the other as it makes no difference to publishing.

**Comment by maxandersen** [comment]
> We used xrefs because it allowed us to construct/preserve those links in the different formats (single html, paged, PDF, etc...) that are used by the portal. If you use link:, you can only ever generate a paged html format, as if you generate anything else those links will no longer work. Also, the use of xref over <<>> was preferred because it was the general format for other tags (link:, image:, include:: etc.).

To be clear our main beef is not between `xref` and `link` but that using `<<` as far as we can see translates to behave like an xref but have the advantage of being the more idiomatic and compact way to  make references in asciidoc. Is reason purely for cosmetic reference and there are no technical issues with `<<` ?

**Comment by hferentschik** [comment]
> We used xrefs because it allowed us to construct/preserve those links in the different formats (single html, paged, PDF, etc...)

I am not quite sure what you mean here with preserve. In case you are concerned that <<>> does somehow tie you to an output format, then the behavior of <<>> is the same as xref. <<>> is a asciidoctor macro for an xref.

>  Also, the use of xref over <<>> was preferred because it was the general format for other tags (link:, image:, include:: etc.).

Ok, I get that. There is a certain unity in using xref. As a long time asciidoctor user it still feels awkward to me, so I am wondering whether this is something which really needs to be enforced.

**Comment by thatdocslady** [comment]
@adellape @vikram-redhat just a friendly ping to see if you had a chance to go through @hferentschik and @maxandersen responses, thanks!

**Comment by vikram-redhat** [comment]
>  Is reason purely for cosmetic reference and there are no technical issues with << ?

There are no technical reasons to use one over the other. We wanted to be consistent in the use of this tag.

**Comment by vikram-redhat** [comment]
> We used xrefs because it allowed us to construct/preserve those links in the different formats (single html, paged, PDF, etc...)

> I am not quite sure what you mean here with preserve. In case you are concerned that <<>> does somehow tie you to an output format, then the behavior of <<>> is the same as xref. <<>> is a asciidoctor macro for an xref.

This seems out of context. I am saying here why we used xrefs over links and not why we used xref over <<>>.

**Comment by thatdocslady** [comment]
@vikram-redhat I guess this was a miscommunication on my part, I wasn't asking about xref/link, but rather of non-prefix ways of tagging links, such as <<>>. I hope this clarifies the question.

**Comment by vikram-redhat** [comment]
@thatdocslady - thanks Mikey. So the only reason we used xrefs over <<>> was to be consistent. Hope that clarifies. I am going to close this issue now, please reopen if otherwise.
