### ISSUE TITLE
[enterprise-4.10] Issue in file networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc

### ISSUE THREAD

**Issue by johnsimcall** [openshift/openshift-docs#45661]
The example for static IP addressing should really include a default route as well.

**Comment by johnsimcall** [comment]
I thought something like this might be more appropriate:

https://github.com/openshift/openshift-docs/pull/45662

https://github.com/openshift/openshift-docs/blob/main/modules/virt-example-nmstate-IP-management.adoc

**Comment by apinnick** [comment]
The nmstate documentation is no longer maintained by the OpenShift Virtualization doc team. It is moving to the networking section. This is the section that needs to be updated: [Static](https://docs.openshift.com/container-platform/4.10/networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.html#virt-example-nmstate-IP-management-static_k8s_nmstate-updating-node-network-config)
I am updating the issue summary so that it is picked up by the correct team.
