### ISSUE TITLE
Advanced installation docs don't link to Ansible

### ISSUE THREAD

**Issue by maxstepanov** [openshift/openshift-docs#4573]
I tried to follow Advanced install with Ansible but there is no link to actual Ansible repository for this type of install, not to mention a versions mess...

**Comment by php-coder** [comment]
@maxstepanov Interesting observation. First of all, Ansible installer repository is here: https://github.com/openshift/openshift-ansible

Also, documentation to what version and what "flavor" did you read? On which site (http://docs.openshift.com or http://docs.openshift.org)? :) Because different types assume a different approaches to get the installer, for example.

**Comment by maxstepanov** [comment]
@php-coder Origin one
https://docs.openshift.org/latest/install_config/install/advanced_install.html

**Comment by vikram-redhat** [comment]
I am going to close this issue as this documentation has changed a fair bit and I am not sure if the original issue stands. Please open a new issue if you think otherwise.
