### ISSUE TITLE
[enterprise-4.10] Issue in file storage/persistent_storage/persistent-storage-ocs.adoc

### ISSUE THREAD

**Issue by lijcam** [openshift/openshift-docs#48337]
### What needs fixing?

This document references a previous version of OpenShift.

**Comment by kelbrown20** [comment]
This issue was addressed in #48154, but one typo is being fixed in #50172

**Comment by kelbrown20** [comment]
Issue was fixed in #50172 
Updated docs: 
- Docs website: https://docs.openshift.com/container-platform/4.10/storage/persistent_storage/persistent-storage-ocs.html
- Customer portal: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/storage/configuring-persistent-storage#red-hat-openshift-data-foundation

Setting to close
