### ISSUE TITLE
[enterprise-4.10] Issue in file installing/disconnected_install/installing-mirroring-disconnected.adoc

### ISSUE THREAD

**Issue by andrea-mh** [openshift/openshift-docs#49530]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/installing/disconnected_install/installing-mirroring-disconnected.html#installation-oc-mirror-installing-plugin_installing-mirroring-disconnected

### What needs fixing?
Add a hyphon in the oc mirror command examples, e.g.
Change:
oc mirror help
To:
oc**-**mirror help

And for subsequent occurrences:
oc mirror --config=./imageset-config.yaml docker://registry.example:5000 

oc mirror --config=./imageset-config.yaml file://<path_to_output_directory> 

oc mirror --from=./mirror_seq1_000000.tar docker://registry.example:5000 

oc mirror help

Many thanks in advance!

**Comment by bergerhoffer** [comment]
Hi @andrea-mh! The `oc-mirror` tool is intended to be installed as a plug-in to the `oc` CLI. When that is done, and you move the binary into your path, the correct command does not use a hyphen between "oc" and "mirror". `oc mirror help` is correct.

If you were to just straight download the binary and run it locally (not as a CLI plug-in), then in that case it would use a hyphen.

Since the docs are correct as is, I am closing this issue. But please feel free to reply or reopen if you have any further questions on this, thanks!
