### ISSUE TITLE
Bug in asciibinder rendering for content that follows a bullet that contains a codeblock + callout

### ISSUE THREAD

**Issue by aireilly** [openshift/openshift-docs#50556]
https://docs.openshift.com/container-platform/4.11/virt/virtual_machines/vm_networking/virt-configuring-sriov-device-for-vms.html#nw-sriov-configuring-device_virt-configuring-sriov-device-for-vms

![image](https://user-images.githubusercontent.com/74046732/191065557-b1117935-e091-47fa-8a05-a2e544883af3.png)

### What needs fixing?
The child bullet directly under the note is not formatted correctly.

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

Whoever takes this, make the change against the `main` branch, and ping me with any questions!

In the quick look I took, it looks like step 1 is missing the `+` character above the code block (should go inside the ifdef, around line 43). But then there is also a `[start=2]` that likely needs to be removed, because it's causing the procedure two have 2 step 2's. 

We'll need to verify in both assemblies that use this module that the procedures work properly. But a member of the docs team can help with this part!

**Comment by void-hr** [comment]
@bergerhoffer @aireilly 
I would like to work on this...

**Comment by void-hr** [comment]
@bergerhoffer @aireilly 
What I have understood is that the child bullet under note is actually point number 2. Instead of removing `[start=2]` we can move  this above the bullet child under note. 
And ***2. Create the  `SriovNetworkNodePolicy` object:*** would be the point number 3.

Please correct me if I am missing something here.

**Comment by void-hr** [comment]
@aireilly should I unassign myself from this issue?

**Comment by aireilly** [comment]
@void-hr yes I guess so sorry! I checked what was needed to report back and fixed it inadvertently 😅

**Comment by void-hr** [comment]
@aireilly no worries, also I want to know that what `+` does to file.

**Comment by aireilly** [comment]
Basicallly it's a "keep with previous directive" that aligns paragraphs with previous bullets, etc. Very handy for complex content. See "Complex content in outline lists" here: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
