### ISSUE TITLE
Document system:masters group

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#5209]
Extracted from https://github.com/openshift/origin/issues/16092#issuecomment-327832066: documentation should mention about `system:masters` group (and probably about `system:cluster-admins`).

**Comment by vikram-redhat** [comment]
@kalexand-rh - PTAL.

**Comment by kalexand-rh** [comment]
@enj, do you still want this documented?

It sounds like we need to say that a member of the `system:masters` group has permission to modify all settings in the cluster, but I'm not sure how someone with the `sudoers` role would impersonate that group instead of the `system:admin` group.

If the clarification of how to access the two different groups is all we need, I think the information would go here, for now: https://docs.openshift.com/container-platform/3.9/architecture/additional_concepts/authentication.html#authentication-impersonation

**Comment by enj** [comment]
> do you still want this documented?

Yes.

> It sounds like we need to say that a member of the system:masters group has permission to modify all settings in the cluster

`system:masters` never receives a deny from any authorization logic even if all RBAC data in the cluster is deleted.

> but I'm not sure how someone with the sudoers role would impersonate that group

`oc ... --as=<any_user> --as-group=system:masters`

> instead of the system:admin group.

`system:admin` is a user, not a group.

> If the clarification of how to access the two different groups is all we need, I think the information would go here, for now: https://docs.openshift.com/container-platform/3.9/architecture/additional_concepts/authentication.html#authentication-impersonation

I do not think any changes are needed to that doc.
