### ISSUE TITLE
[enterprise-4.8] Issue in file updating/index.adoc

### ISSUE THREAD

**Issue by rhgpereira** [openshift/openshift-docs#52245]
### Which section(s) is the issue in?

Updating clusters overview (https://docs.openshift.com/container-platform/4.8/updating/index.html)

### What needs fixing?

Add a new section in OCP 4.8 upgrade warning users of the need to review the need to ensure their OCS storage operator is +- 1 version and only then they can upgrade. So, if OCS operator is 4.6.15 they cannot upgrade to 4.9 till ons operator is upgraded to 4.8.15. Goal is do not break and block after they come to OCP 4.8.51

The OCS documentation states in the section **Update considerations**:
```
Red Hat recommends using the same version of Red Hat OpenShift Container Platform with Red Hat OpenShift Container Storage.

See the [Interoperability Matrix|https://access.redhat.com/articles/4731161] for more information about supported combinations of OpenShift Container Platform and OpenShift Container Storage.
```

The above consideration is not present in the OCP Updating Clusters documentation and it would be good (improving the customer experience) consider adding a link to the [Interoperability Matrix](https://access.redhat.com/articles/4731161) and an update considerations note.

**Comment by LalatenduMohanty** [comment]
Adding the documentation is not the right solution for this as customer can easily miss the note in the documentation. 

In OCP we  have `Upgradeable` status condition [1] Which OCS storage operator should set to false so that the next minor upgrade will not break the cluster.  Do you know if the cluster has an `upgradeble=false` status condition?

[1] https://github.com/openshift/api/blob/master/config/v1/types_cluster_operator.go#L179-L190
