### ISSUE TITLE
[online] Issue in file upgrading/rosa-upgrading.adoc

### ISSUE THREAD

**Issue by Simranpal** [openshift/openshift-docs#52546]
### Which section(s) is the issue in?

Upgrading a ROSA cluster
https://deploy-preview-41923--osdocs.netlify.app/openshift-rosa/latest/upgrading/rosa-upgrading.html#rosa-sts-upgrading-a-cluster

### What needs fixing?

Duplicate entries for the 3 methods to upgrade Red Hat OpenShift Service on AWS (ROSA) clusters

![Screenshot from 2022-11-07 10-11-18](https://user-images.githubusercontent.com/8645166/200383950-8a11a19b-5cb3-4977-b602-5aa58d220460.png)

**Comment by skopacz1** [comment]
Closing this issue because the [live documentation](https://docs.openshift.com/rosa/upgrading/rosa-upgrading.html#rosa-sts-upgrading-a-cluster) no longer has the duplicate bullet list. It seems that the error was removed as part of #44907 

Feel free to open another ticket if you have further concerns! Thanks
