### ISSUE TITLE
[dedicated] Issue in file osd_architecture/osd-understanding.adoc

### ISSUE THREAD

**Issue by faldanarh** [openshift/openshift-docs#55184]
### Which section(s) is the issue in?
Understanding OpenShift Dedicated

### What needs fixing?
The links on this page redirect to old OCP documentation.

**Comment by rolfedh** [comment]
Hi, @faldanarh. Thanks for reporting this issue. I'm adding the URL to make it easier for the writing team to find this issue: https://docs.openshift.com/dedicated/osd_architecture/osd-understanding.html#osd-intro_osd-understanding

**Comment by rolfedh** [comment]
I'm marking this as a good candidate for Hacktoberfest.

If someone is interested in taking it, please make the change against the main branch.
The cause of the issue is that some link URLs in `modules/osd-intro.adoc` contain hard-coded version version numbers, `4.7`. 
We need to replace them with an asciidoc attribute, `{ocp-version}`.

**Comment by faldanarh** [comment]
Thanks, @rolfedh .
