### ISSUE TITLE
[enterprise-4.12] Issue in file networking/ingress-node-firewall-operator.adoc

### ISSUE THREAD

**Issue by freedge** [openshift/openshift-docs#55291]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.12/networking/ingress-node-firewall-operator.html#nw-infw-operator-cr_ingress-node-firewall-operator

### What needs fixing?

warning claims:
The maximum transmission units (MTU) parameter is 4Kb (kilobytes) in OpenShift Container Platform 4.12.

we use MTU=9000 since a thousand years so this must be a typo?

**Comment by freedge** [comment]
also typo 3 lines below
 To *delploy* the Ingress Node Firewall Operator

**Comment by apinnick** [comment]
> also typo 3 lines below To _delploy_ the Ingress Node Firewall Operator

@freedge I fixed the typo. [PR55293](https://github.com/openshift/openshift-docs/pull/55293).

**Comment by apinnick** [comment]
@JoeAldinger 
Please check.

**Comment by msherif1234** [comment]
@freedge regarding the MTU limitation this XDP MTU limitation and it exists in RHEL8 and will be fixed in RHEL9 when multi-buffer apis is avaliable, I already have PR with all required changes just waiting on rhel9 to land here is PR for reference https://github.com/openshift/ingress-node-firewall/pull/262

**Comment by freedge** [comment]
ok. Thanks for the precision. Then the documentation is correct unfortunately. Thank you.
