### ISSUE TITLE
[online] The route is not accepting traffic yet because it has not been admitted by a router.

### ISSUE THREAD

**Issue by syui** [openshift/openshift-docs#6086]
I am using OpenShift Online Starter.

However, errors are generated when creating Routes.

```sh
$ oc expose svc/xxxxx
```

`The route is not accepting traffic yet because it has not been admitted by a router.`

https://docs.openshift.com/online/dev_guide/routes.html

**Comment by ahardin-rh** [comment]
@tiwillia @Miciah Please advise

**Comment by syui** [comment]
I solved the problem.

But this time a new problem has occurred.

> An error occurred creating the route. Reason: Route "xxxxx" is invalid: spec.host: Forbidden: you do not have permission to set the host field of the route

**Comment by syui** [comment]
In addition, if you do not reload many times `Application is not available`.

example : http://cachet-tapp.1d35.starter-us-east-1.openshiftapps.com/

**Comment by mrinx** [comment]
@syui, can you tell me how did you solve the problem?

I still have a problem with my route, no matter how long I wait.

`... either the administrator has not installed a router or the router is not selecting this route.`

I'm also on `1d35.starter-us-east-1.openshiftapps.com`

**Comment by syui** [comment]
@mrinx sorry, I put timed.

The error disappeared the day after I wrote the issue.

**Comment by jkkj93** [comment]
I met the same problem as syui.

**Comment by MartinMelis21** [comment]
Currently facing the same issue (using Starter plan). Having a Java application on Tomcat 7, built and deployed currectly (curl 0.0.0.0:8080 on the pod works fine), but unable to create the route. 
Progress message: The route is not accepting traffic yet because it has not been admitted by a router.

After checking  oc adm router --dry-run error is returned: Router "router" service does not exist.

After trying to create a router with  oc adm router
error pops up: router could not be created; could not retrieve list of security constraints to verify service account "router": User "martinmelis" cannot list all securitycontextconstraints in the clu
ster

**Comment by Miciah** [comment]
@syui and @jkkj93, custom domains is only included as part of the Pro plan, not Starter.  This is documented in the plan descriptions, but the restriction on custom domains was not consistently enforced on Starter, so confusion is understandable.  Besides that, are you still seeing problems?

@mrinx and @MartinMelis21, can you provide the output of `oc get routes -o json`? Perhaps there will be more information in the route `.spec` or `.status` fields.

Note that the router can take a few minutes to admit a route during times of high contention.

Note also that `oc adm` commands are generally intended for the cluster administrator to use.

**Comment by mrinx** [comment]
@Miciah, I have a working route now, it started working for me again on Saturday, I didn't mess with it since then. In my case it took longer than minutes, it was in hours. And before that I was waiting a whole day or so - without any success.

Do I understand correctly, that the `creationTimestamp` is the time I asked for the route to be created, and the `lastTransitionTime` is the time when the route was accepted by the router?

```{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "v1",
            "kind": "Route",
            "metadata": {
                "annotations": {
                    "openshift.io/host.generated": "true"
                },
                "creationTimestamp": "2017-11-03T17:34:09Z",
                ...
            },
            "spec": {
                "host": "x-y.1d35.starter-us-east-1.openshiftapps.com",
                "port": {
                    "targetPort": "8080-tcp"
                },
                "to": {
                    "kind": "Service",
                    "name": "x",
                    "weight": 100
                },
                "wildcardPolicy": "None"
            },
            "status": {
                "ingress": [
                    {
                        "conditions": [
                            {
                                "lastTransitionTime": "2017-11-04T05:41:27Z",
                                "status": "True",
                                "type": "Admitted"
                            }
                        ],
                        ...
                    }
                ]
            }
        }
    ],
    ...
}
```

**Comment by syui** [comment]
@Miciah No

**Comment by jkkj93** [comment]
@Miciah Got it.Thank you for answering.
