### ISSUE TITLE
OpenShift 3.8/3.9 Release Notes Tracker

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#6458]

**Comment by liggitt** [comment]
* The autoscaling/v2alpha1 API group has been removed
* batch/v2alpha1 SchedueldJob objects are no longer supported. Use CronJobs instead.
* `openshift start node` requires swap to be disabled. This is already done as part of the ansible node install.

**Comment by michaelgugino** [comment]
In an effort to provide greater flexibility for users, we have removed several instances of 'become: no' on certain tasks and playbooks inside of openshift-anisble.  These statements were primarily applied on 'local_action' and 'delegate_to: localhost' commands for creating temporary files on the host running ansible.

If a user is running ansible from a host that does not allow passwordless sudo, some of these commands may fail of the user runs ansible-playbook with the '-b' (become) command line switch, or has 'ansible_become=True' applied to localhost in inventory or group_vars.

Elevated permissions are not requried on the localhost when running openshift-ansible plays.

If target hosts (where openshift is being deployed) require the use of become, it is recommended to add "ansible_become=True" for those hosts or groups in inventory or group_vars/host_vars.

If the user is running as root on the localhost, or connection to the root user on the remote hosts instead of using become, no change should be noticed.

**Comment by vrutkovs** [comment]
Default values for `template_service_broker_prefix` and `template_service_broker_image_name` in installer have been updated to be consistent with other settings.

Previous value:
 - `template_service_broker_prefix="registry.example.com/"`
 - `template_service_broker_image_name="origin-template-service-broker"` or `template_service_broker_image_name="ose-template-service-broker"`
New value:
- `template_service_broker_prefix="registry.example.com/ose-"` or `template_service_broker_prefix="registry.example.com/origin-"`
- `template_service_broker_image_name="template-service-broker"`

**Comment by ahardin-rh** [comment]
openshift/origin#18093 deprecated several oc secrets sub commands. This PR changes our docs not to use them, but instead use the supported versions.

This will require also release notes, something along the lines:

OpenShfit 3.9 deprecates following oc secrets sub commands:   new, new-basicauth, new-dockercfg, new-sshauth in favor of oc create secret. 

Per https://github.com/openshift/openshift-docs/pull/7262#issue-290508371

**Comment by bmcelvee** [comment]
Add depreciation announcement for Hawkular. Trello card: to be added.

**Comment by sdodson** [comment]
Starting in OCP 3.9 ansible needs to be installed via the rhel-7-server-ansible-2.4-rpms channel which is included in RHEL subscriptions. #7890

**Comment by mfojtik** [comment]
The core workloads API, which is composed of the DaemonSet, Deployment, ReplicaSet, and StatefulSet kinds, has been promoted to GA stability in the apps/v1 group version. As such, the apps/v1beta2 group version is deprecated, and all new code should use the kinds in the apps/v1 group version. For OpenShift this means the StatefulSets, DaemonSet and Deployments are now stable and supported and no longer "beta".

**Comment by liggitt** [comment]
@openshift/team-documentation can this be closed now?

**Comment by vikram-redhat** [comment]
@liggitt I believe so, but will wait for @ahardin-rh to confirm today.

**Comment by ahardin-rh** [comment]
@liggitt @vikram-redhat Yes, closing now. Thanks for the reminder!
