### ISSUE TITLE
The term "application" is still getting used 

### ISSUE THREAD

**Issue by rassie** [openshift/openshift-docs#733]
I've been trying to get through the "getting started" chapters and especially the [Creating new applications](https://docs.openshift.com/enterprise/3.0/dev_guide/new_app.html) part and couldn't wrap my head around the application concept, until I found a clear stance that ["application" as a term doesn't exist anymore in OSEv3](https://docs.openshift.com/enterprise/3.0/whats_new/terminology.html). So I suppose it probably should be gone from the documentation too, hence this issue.

**Comment by sosiouxme** [comment]
Application as an API entity doesn't exist and won't exist because the scope of what's included in an application can vary widely (from a single pod up to massively scaled project-spanning tiers). But the concept of an application still exists, and it can be useful to talk about it as users will be thinking in terms of apps (which is also hinted at with the `oc new-app` command). We just need to be very clear that "application" is a very amorphous term with no specific meaning in OpenShift, and use more precise terms ("pod", "deployment", "DeploymentConfig", "project") if that is what is really meant. In this section, we're definitely talking about the components that wire together into an application so I don't see a problem with the title.

**Comment by vikram-redhat** [comment]
Agree with @sosiouxme. Closing this issue. Please reopen if you think otherwise.
