### ISSUE TITLE
apb: cli-tooling guide uses wrong container image name 

### ISSUE THREAD

**Issue by pilhuhn** [openshift/openshift-docs#7496]
https://docs.openshift.org/latest/apb_devel/cli_tooling.html

says

> Pull the container:
> 
> $ docker pull docker.io/ansibleplaybookbundle/apb[:<tag>]

which fails:

```
$ docker run docker.io/ansibleplaybookbundle/apb
Unable to find image 'ansibleplaybookbundle/apb:latest' locally
Pulling repository docker.io/ansibleplaybookbundle/apb
docker: Error: image ansibleplaybookbundle/apb:latest not found.
```

Using `abp-tools` works

```
$ docker pull docker.io/ansibleplaybookbundle/apb-tools:latest
latest: Pulling from ansibleplaybookbundle/apb-tools
Digest: sha256:777ad59a235e5576107860041674109d03241d8854eab8adfb87cb6f9c0d4c17
Status: Image is up to date for ansibleplaybookbundle/apb-tools:latest
```

**Comment by rkratky** [comment]
Why hasn't the PR been merged for so long? It's an easy fix, and the mistake in docs is very confusing for users.

Also, the same bug has long been fixed in https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/apb_cli.md#running-from-a-container (reported in https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/issues/172).

**Comment by vikram-redhat** [comment]
@ahardin-rh - can you take a look at this today? Tagging you on another one and a related BZ. These should be simple fixes, but confirm with @adellape

**Comment by adellape** [comment]
Sorry, the PR wasn't originally submitted to our repo. I've grabbed it and submitted it via https://github.com/openshift/openshift-docs/pull/10511.
