### ISSUE TITLE
Security instructions aren't framed in a way that educates admins about tradeoffs

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-docs#759]
Specifically https://docs.openshift.org/latest/admin_guide/manage_scc.html needs to be reorganized into a topic around managing security of the cluster with the following topics:
1. Controlling what users can do and an explanation of the default roles
2. Controlling what pods can do - the defaults, and how you selectively relax them
   1. The examples should _not_ relax permissions for the whole cluster, it should relax them for a given project.
3. Controlling what builds can do - for instance, that Docker builds can run as root and how to disable them.

List other useful things like how to disable all security, how you would centralize all your Docker builds into one namespace for security, etc.

**Comment by smarterclayton** [comment]
@pweil-

**Comment by smarterclayton** [comment]
It's possible there should be two topics - container security and cluster security, but for now they intertwine.

**Comment by smarterclayton** [comment]
Also talk about how exec and logs may require security limitations and how those can be disabled.

**Comment by adellape** [comment]
> Controlling what users can do and an explanation of the default roles

@smarterclayton Do you feel like part of this is satisfied in the related arch topic (https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#security-context-constraints), or should maybe be moved or better linked to?

**Comment by smarterclayton** [comment]
No - I'm referring to basic roles (project admin, editor, viewer) and what
they can do in pods (create / delete pods, exec into them, see logs) and
how security context constraints can restrict that.  Basically, we are
lacking a "how do I secure my cluster" that answers both the most common
questions and well as explains the separation of responsibilities and use
cases.

On Wed, Jul 15, 2015 at 4:18 PM, Alex Dellapenta <notifications@github.com>
wrote:

> Controlling what users can do and an explanation of the default roles
>
> @smarterclayton <https://github.com/smarterclayton> Do you feel like part
> of this is satisfied in the related arch topic (
> https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#security-context-constraints),
> or should maybe be moved or better linked to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/openshift-docs/issues/759#issuecomment-121733938>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by adellape** [comment]
(Not sure anymore what the state of the cited topics were when this was opened, but...)

The [Roles](https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#roles) section describes what the default roles can do, followed by [Security Context Constraints](https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#security-context-constraints) section, which describes some of the default SCCs. The [Managing Security Context Constraints](https://docs.openshift.org/latest/admin_guide/manage_scc.html) topic has the [How Do I?](https://docs.openshift.org/latest/admin_guide/manage_scc.html#how-do-i) section which lists common scenarios and procedures using SCCs, some of which include relaxing security. The new [Container Security Guide](https://docs.openshift.org/latest/security/deployment.html#security-deployment-sccs) also touches on SCCs (though links to the Architecture topic for more info).

I'm going to close this for now due to inactivity, but @pweil- if you have suggestions (or a recommendation on someone I can reach out to) about closing any remaining gaps here, please re-open/LMK.
