### ISSUE TITLE
SELinux for NFS volumes

### ISSUE THREAD

**Issue by sosiouxme** [openshift/openshift-docs#772]
https://github.com/openshift/openshift-docs/blob/master/admin_guide/persistent_storage_nfs.adoc#selinux-and-nfs-export-settings

The callout on this is confusing as it looks like part of the command. No real reason for it to be there:

    # setsebool -P virt_use_nfs 1 (1)

Also we should note that you can expect the ansible install script to do this for you.

**Comment by markturansky** [comment]
Agreed.  (1) will cause errors for anyone cutting and pasting.

**Comment by adellape** [comment]
The callout rendering problems on the Customer Portal builds is a known issue with the docs branding:

https://github.com/openshift/openshift-docs/issues/547
https://bugzilla.redhat.com/show_bug.cgi?id=1236041

These issues are not present on the docs.openshift builds:

https://docs.openshift.com/enterprise/3.0/admin_guide/persistent_storage_nfs.html#selinux-and-nfs-export-settings

Hopefully that overall issue can get addressed soon because it's pretty terrible. But for this particular issue, agreed, having the (1) information be specifically a callout isn't necessary; I'll rework it to avoid this issue here.

**Comment by vikram-redhat** [comment]
IIUC, this is no longer an issue. @adellape re-open if I am wrong.
