### ISSUE TITLE
Include resource management (quota,limits,etc) in the osev3 admin guide 

### ISSUE THREAD

**Issue by plse** [openshift/openshift-docs#809]
Although quota, resource limits are explained in the dev guide, it makes more sense to include this information in the admin guide, as typically in a company, the admin/operator of OSE environment would like to configure and control the resources for their developers ...

**Comment by sosiouxme** [comment]
I agree that there should be a corresponding admin section. All the more so because a developer cannot actually create or delete LimitRange or ResourceQuota objects. 

https://github.com/openshift/openshift-docs/blob/master/dev_guide/compute_resources.adoc looks like it is sufficiently developer-targeted.

https://github.com/openshift/openshift-docs/blob/master/dev_guide/limits.adoc looks like it could be wholesale moved into the admin guide. As it is, it's redundant and makes it sound like users can set their project limits, which they can't (AFAIK only a cluster-admin can).

Not sure where the discussion of quota is anymore.
