### ISSUE TITLE
Unclear which upgrade steps should we do first, standard upgrade or release specific

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#849]
There are standard upgrade stpes[1] and release specific steps[2]. It is not clear which steps should we do first.

[1] https://docs.openshift.com/enterprise/3.0/admin_guide/upgrades.html
[2] https://docs.openshift.com/enterprise/3.0/admin_guide/upgrades.html#openshift-enterprise-3-0-1-0

**Comment by adellape** [comment]
Since it could vary from release to release, the Overview states:

> Before you begin your upgrade, familiarize yourself with the entire procedure. Specific releases may require additional steps to be performed at key points during the standard upgrade process.

In this case, the specific 3.0.1.0 step takes place right before the standard router upgrade, as described in the 3.0.1.0 section. However I also added an "Important" box to the router upgrade section yesterday via https://github.com/openshift/openshift-docs/pull/845.

Going to try to get that cherry-picked into the OSE build ASAP.

**Comment by nak3** [comment]
Thank you for your answer. I understand and https://github.com/openshift/openshift-docs/pull/845 looks good.  As for this issue, I can close now.

Again, thank you for your quick reply.

**Comment by adellape** [comment]
@nak3 https://github.com/openshift/openshift-docs/pull/845 went live last night, btw:

https://docs.openshift.com/enterprise/3.0/admin_guide/upgrades.html#upgrading-the-router

https://access.redhat.com/documentation/en/openshift-enterprise/version-3.0/openshift-enterprise-30-administrator-guide#upgrading-the-router

**Comment by nak3** [comment]
Yes, I checked it. Thank you so much @adellape
