### ISSUE TITLE
Configuring the DNS wilcard when there are multiple routers

### ISSUE THREAD

**Issue by mikemowgli** [openshift/openshift-docs#9502]
Hello,
This section (https://docs.openshift.org/latest/install_config/install/prerequisites.html#wildcard-dns-prereq) describes how to configure an external DNS to point to an openshift router to resolve applications running in the cluster.

However, on my cluster, I have 3 router pods, deployed on all 3 infra-nodes.
If I configure 3 wildcard DNS records, to bind with all 3 infra nodes, then a request to a specific application might be handled by the wrong record.
How should the wildcard DNS be configured to address a multiple router situation?

thank you

**Comment by vikram-redhat** [comment]
@sdodson @knobunc is this something the docs should cover? Or is this an edge case?


cc: @aheslin @bfallonf @adellape

**Comment by sdodson** [comment]
You should configure your wildcard as a round robin pointing at your three router pods rather than creating three wildcard hostnames. Alternatively you could configure the wildcard to point at a Virtual IP or load balancer that routes traffic to all of your routers instead.

I'm not sure whether this requires documentation clarification or not.

**Comment by vikram-redhat** [comment]
@bfallonf - can you please take a look and assess if it requires clarification?

**Comment by vikram-redhat** [comment]
I am closing this issue as this does seem to be edge case.
